// src/main/webapp/app/entities/category/category-update.tsx
import React from 'react';
import {connect} from 'react-redux';
import {Link, RouteComponentProps} from 'react-router-dom';
import {Button, Col, Label, Row} from 'reactstrap';
import {AvForm, AvGroup, AvInput} from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import {byteSize, openFile, setFileData, Translate} from 'react-jhipster';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {IRootState} from 'app/shared/reducers';
import {getEntities as getLibraries} from 'app/entities/library/library.reducer';
import {createEntity, getEntity, reset, setBlob, updateEntity} from './category.reducer';

// tslint:disable-next-line:no-unused-variable

export interface ICategoryUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {
}

export interface ICategoryUpdateState {
  isNew: boolean;
  libraryId: string;
}

export class CategoryUpdate extends React.Component<ICategoryUpdateProps, ICategoryUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      libraryId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getLibraries();
  }

  onBlobChange = (isAnImage, name) => event => {
    setFileData(event, (contentType, data) => this.props.setBlob(name, data, contentType), isAnImage);
  };

  clearBlob = name => () => {
    this.props.setBlob(name, undefined, undefined);
  };

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const {categoryEntity} = this.props;
      const entity = {
        ...categoryEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/category');
  };

  render() {
    const {categoryEntity, libraries, loading, updating} = this.props;
    const {isNew} = this.state;

    const {images, imagesContentType} = categoryEntity;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="iCounselingApp.category.home.createOrEditLabel">
              <Translate contentKey="iCounselingApp.category.home.createOrEditLabel">Create or edit a
                Category</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : categoryEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="category-id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="category-id" type="text" className="form-control" name="id" required readOnly/>
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <AvGroup>
                    <Label id="imagesLabel" for="images">
                      <Translate contentKey="iCounselingApp.category.images">Images</Translate>
                    </Label>
                    <br/>
                    {images ? (
                      <div>
                        <a onClick={openFile(imagesContentType, images)}>
                          <Translate contentKey="entity.action.open">Open</Translate>
                        </a>
                        <br/>
                        <Row>
                          <Col md="11">
                            <span>
                              {imagesContentType}, {byteSize(images)}
                            </span>
                          </Col>
                          <Col md="1">
                            <Button color="danger" onClick={this.clearBlob('images')}>
                              <FontAwesomeIcon icon="times-circle"/>
                            </Button>
                          </Col>
                        </Row>
                      </div>
                    ) : null}
                    <input id="file_images" type="file" onChange={this.onBlobChange(false, 'images')}/>
                    <AvInput type="hidden" name="images" value={images}/>
                  </AvGroup>
                </AvGroup>
                <AvGroup>
                  <Label id="categoryTypeLabel" for="category-categoryType">
                    <Translate contentKey="iCounselingApp.category.categoryType">Category Type</Translate>
                  </Label>
                  <AvInput
                    id="category-categoryType"
                    type="select"
                    className="form-control"
                    name="categoryType"
                    value={(!isNew && categoryEntity.categoryType) || 'ROMANCE'}
                  >
                    <option value="ROMANCE">
                      <Translate contentKey="iCounselingApp.CategoryType.ROMANCE"/>
                    </option>
                    <option value="ARTS_PHOTOGRAPHY">
                      <Translate contentKey="iCounselingApp.CategoryType.ARTS_PHOTOGRAPHY"/>
                    </option>
                    <option value="BIOGRAPHIES_MEMOIRS">
                      <Translate contentKey="iCounselingApp.CategoryType.BIOGRAPHIES_MEMOIRS"/>
                    </option>
                    <option value="BUSINESS_INVESTING">
                      <Translate contentKey="iCounselingApp.CategoryType.BUSINESS_INVESTING"/>
                    </option>
                    <option value="CHILDREN_BOOKS">
                      <Translate contentKey="iCounselingApp.CategoryType.CHILDREN_BOOKS"/>
                    </option>
                    <option value="COOKBOOKS_FOOD">
                      <Translate contentKey="iCounselingApp.CategoryType.COOKBOOKS_FOOD"/>
                    </option>
                    <option value="HISTORY">
                      <Translate contentKey="iCounselingApp.CategoryType.HISTORY"/>
                    </option>
                    <option value="LOTERATURE_FICTION">
                      <Translate contentKey="iCounselingApp.CategoryType.LOTERATURE_FICTION"/>
                    </option>
                    <option value="MYSTERY_THRILLER_SUSPENSE">
                      <Translate contentKey="iCounselingApp.CategoryType.MYSTERY_THRILLER_SUSPENSE"/>
                    </option>
                    <option value="SCIENCE_FICTION_FANTASY">
                      <Translate contentKey="iCounselingApp.CategoryType.SCIENCE_FICTION_FANTASY"/>
                    </option>
                    <option value="TEEN_YOUNG_ADULT_BOOKS">
                      <Translate contentKey="iCounselingApp.CategoryType.TEEN_YOUNG_ADULT_BOOKS"/>
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="category-library">
                    <Translate contentKey="iCounselingApp.category.library">Library</Translate>
                  </Label>
                  <AvInput id="category-library" type="select" className="form-control" name="libraryId">
                    <option value="" key="0"/>
                    {libraries
                      ? libraries.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/category" replace color="info">
                  <FontAwesomeIcon icon="arrow-left"/>
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save"/>
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  libraries: storeState.library.entities,
  categoryEntity: storeState.category.entity,
  loading: storeState.category.loading,
  updating: storeState.category.updating,
  updateSuccess: storeState.category.updateSuccess
});

const mapDispatchToProps = {
  getLibraries,
  getEntity,
  updateEntity,
  setBlob,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CategoryUpdate);

// src/main/webapp/app/entities/category/category-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService, JhiDataUtils } from 'ng-jhipster';
import { ICategory, Category } from 'app/shared/model/category.model';
import { CategoryService } from './category.service';
import { ILibrary } from 'app/shared/model/library.model';
import { LibraryService } from 'app/entities/library';

@Component({
  selector: 'jhi-category-update',
  templateUrl: './category-update.component.html'
})
export class CategoryUpdateComponent implements OnInit {
  isSaving: boolean;

  libraries: ILibrary[];

  editForm = this.fb.group({
    id: [],
    images: [],
    imagesContentType: [],
    categoryType: [null, [Validators.required]],
    libraryId: []
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected jhiAlertService: JhiAlertService,
    protected categoryService: CategoryService,
    protected libraryService: LibraryService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ category }) => {
      this.updateForm(category);
    });
    this.libraryService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ILibrary[]>) => mayBeOk.ok),
        map((response: HttpResponse<ILibrary[]>) => response.body)
      )
      .subscribe((res: ILibrary[]) => (this.libraries = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(category: ICategory) {
    this.editForm.patchValue({
      id: category.id,
      images: category.images,
      imagesContentType: category.imagesContentType,
      categoryType: category.categoryType,
      libraryId: category.libraryId
    });
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }

  setFileData(event, field: string, isImage) {
    return new Promise((resolve, reject) => {
      if (event && event.target && event.target.files && event.target.files[0]) {
        const file = event.target.files[0];
        if (isImage && !/^image\//.test(file.type)) {
          reject(`File was expected to be an image but was found to be ${file.type}`);
        } else {
          const filedContentType: string = field + 'ContentType';
          this.dataUtils.toBase64(file, base64Data => {
            this.editForm.patchValue({
              [field]: base64Data,
              [filedContentType]: file.type
            });
          });
        }
      } else {
        reject(`Base64 data was not set as file could not be extracted from passed parameter: ${event}`);
      }
    }).then(
      () => console.log('blob added'), // sucess
      this.onError
    );
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const category = this.createFromForm();
    if (category.id !== undefined) {
      this.subscribeToSaveResponse(this.categoryService.update(category));
    } else {
      this.subscribeToSaveResponse(this.categoryService.create(category));
    }
  }

  private createFromForm(): ICategory {
    return {
      ...new Category(),
      id: this.editForm.get(['id']).value,
      imagesContentType: this.editForm.get(['imagesContentType']).value,
      images: this.editForm.get(['images']).value,
      categoryType: this.editForm.get(['categoryType']).value,
      libraryId: this.editForm.get(['libraryId']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICategory>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackLibraryById(index: number, item: ILibrary) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-category-heading" jhiTranslate="iCounselingApp.category.home.createOrEditLabel">Create or edit a Category</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.category.images" for="field_images">Images</label>
                    <div>
                        <div *ngIf="editForm.get('images').value" class="form-text text-danger clearfix">
                            <a class="pull-left" (click)="openFile(editForm.get('imagesContentType').value, editForm.get('images').value)" jhiTranslate="entity.action.open">open</a><br>
                            <span class="pull-left">{{editForm.get('imagesContentType').value}}, {{byteSize(editForm.get('images').value)}}</span>
                            <button type="button" (click)="editForm.patchValue({images: null});editForm.patchValue({imagesContentType: null});"
                                    class="btn btn-secondary btn-xs pull-right">
                                <fa-icon [icon]="'times'"></fa-icon>
                            </button>
                        </div>
                        <input type="file" id="file_images" (change)="setFileData($event, 'images', false)" jhiTranslate="entity.action.addblob"/>
                    </div>
                    <input type="hidden" class="form-control" name="images" id="field_images"
                           formControlName="images"/>
                    <input type="hidden" class="form-control" name="imagesContentType" id="field_imagesContentType"
                           formControlName="imagesContentType" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.category.categoryType" for="field_categoryType">Category Type</label>
                    <select class="form-control" name="categoryType" formControlName="categoryType" id="field_categoryType">
                        <option value="ROMANCE">{{'iCounselingApp.CategoryType.ROMANCE' | translate}}</option>
                        <option value="ARTS_PHOTOGRAPHY">{{'iCounselingApp.CategoryType.ARTS_PHOTOGRAPHY' | translate}}</option>
                        <option value="BIOGRAPHIES_MEMOIRS">{{'iCounselingApp.CategoryType.BIOGRAPHIES_MEMOIRS' | translate}}</option>
                        <option value="BUSINESS_INVESTING">{{'iCounselingApp.CategoryType.BUSINESS_INVESTING' | translate}}</option>
                        <option value="CHILDREN_BOOKS">{{'iCounselingApp.CategoryType.CHILDREN_BOOKS' | translate}}</option>
                        <option value="COOKBOOKS_FOOD">{{'iCounselingApp.CategoryType.COOKBOOKS_FOOD' | translate}}</option>
                        <option value="HISTORY">{{'iCounselingApp.CategoryType.HISTORY' | translate}}</option>
                        <option value="LOTERATURE_FICTION">{{'iCounselingApp.CategoryType.LOTERATURE_FICTION' | translate}}</option>
                        <option value="MYSTERY_THRILLER_SUSPENSE">{{'iCounselingApp.CategoryType.MYSTERY_THRILLER_SUSPENSE' | translate}}</option>
                        <option value="SCIENCE_FICTION_FANTASY">{{'iCounselingApp.CategoryType.SCIENCE_FICTION_FANTASY' | translate}}</option>
                        <option value="TEEN_YOUNG_ADULT_BOOKS">{{'iCounselingApp.CategoryType.TEEN_YOUNG_ADULT_BOOKS' | translate}}</option>
                    </select>
                    <div *ngIf="editForm.get('categoryType').invalid && (editForm.get('categoryType').dirty || editForm.get('categoryType').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('categoryType').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.category.library" for="field_library">Library</label>
                    <select class="form-control" id="field_library" name="library" formControlName="libraryId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="libraryOption.id" *ngFor="let libraryOption of libraries; trackBy: trackLibraryById">{{libraryOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
