// src/main/webapp/app/entities/education/education-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IEducation, Education } from 'app/shared/model/education.model';
import { EducationService } from './education.service';
import { ICounselor } from 'app/shared/model/counselor.model';
import { CounselorService } from 'app/entities/counselor';
import { IVisitor } from 'app/shared/model/visitor.model';
import { VisitorService } from 'app/entities/visitor';

@Component({
  selector: 'jhi-education-update',
  templateUrl: './education-update.component.html'
})
export class EducationUpdateComponent implements OnInit {
  isSaving: boolean;

  counselors: ICounselor[];

  visitors: IVisitor[];

  editForm = this.fb.group({
    id: [],
    type: [null, [Validators.required]]
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected educationService: EducationService,
    protected counselorService: CounselorService,
    protected visitorService: VisitorService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ education }) => {
      this.updateForm(education);
    });
    this.counselorService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICounselor[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICounselor[]>) => response.body)
      )
      .subscribe((res: ICounselor[]) => (this.counselors = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.visitorService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IVisitor[]>) => mayBeOk.ok),
        map((response: HttpResponse<IVisitor[]>) => response.body)
      )
      .subscribe((res: IVisitor[]) => (this.visitors = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(education: IEducation) {
    this.editForm.patchValue({
      id: education.id,
      type: education.type
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const education = this.createFromForm();
    if (education.id !== undefined) {
      this.subscribeToSaveResponse(this.educationService.update(education));
    } else {
      this.subscribeToSaveResponse(this.educationService.create(education));
    }
  }

  private createFromForm(): IEducation {
    return {
      ...new Education(),
      id: this.editForm.get(['id']).value,
      type: this.editForm.get(['type']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IEducation>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackCounselorById(index: number, item: ICounselor) {
    return item.id;
  }

  trackVisitorById(index: number, item: IVisitor) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-education-heading" jhiTranslate="iCounselingApp.education.home.createOrEditLabel">Create or edit a Education</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.education.type" for="field_type">Type</label>
                    <select class="form-control" name="type" formControlName="type" id="field_type">
                        <option value="ASSOCIATE_DEGREE">{{'iCounselingApp.EducationDegree.ASSOCIATE_DEGREE' | translate}}</option>
                        <option value="BACHELOR_DEGREE">{{'iCounselingApp.EducationDegree.BACHELOR_DEGREE' | translate}}</option>
                        <option value="DOCOTRAL_DEGREE">{{'iCounselingApp.EducationDegree.DOCOTRAL_DEGREE' | translate}}</option>
                        <option value="MASTER_DEGREE">{{'iCounselingApp.EducationDegree.MASTER_DEGREE' | translate}}</option>
                    </select>
                    <div *ngIf="editForm.get('type').invalid && (editForm.get('type').dirty || editForm.get('type').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('type').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/education/education-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ICounselor } from 'app/shared/model/counselor.model';
import { getEntities as getCounselors } from 'app/entities/counselor/counselor.reducer';
import { IVisitor } from 'app/shared/model/visitor.model';
import { getEntities as getVisitors } from 'app/entities/visitor/visitor.reducer';
import { getEntity, updateEntity, createEntity, reset } from './education.reducer';
import { IEducation } from 'app/shared/model/education.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer, convertDateTimeToServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IEducationUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface IEducationUpdateState {
  isNew: boolean;
  counselorId: string;
  visitorId: string;
}

export class EducationUpdate extends React.Component<IEducationUpdateProps, IEducationUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      counselorId: '0',
      visitorId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getCounselors();
    this.props.getVisitors();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { educationEntity } = this.props;
      const entity = {
        ...educationEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/education');
  };

  render() {
    const { educationEntity, counselors, visitors, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="iCounselingApp.education.home.createOrEditLabel">
              <Translate contentKey="iCounselingApp.education.home.createOrEditLabel">Create or edit a Education</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : educationEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="education-id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="education-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="typeLabel" for="education-type">
                    <Translate contentKey="iCounselingApp.education.type">Type</Translate>
                  </Label>
                  <AvInput
                    id="education-type"
                    type="select"
                    className="form-control"
                    name="type"
                    value={(!isNew && educationEntity.type) || 'ASSOCIATE_DEGREE'}
                  >
                    <option value="ASSOCIATE_DEGREE">
                      <Translate contentKey="iCounselingApp.EducationDegree.ASSOCIATE_DEGREE" />
                    </option>
                    <option value="BACHELOR_DEGREE">
                      <Translate contentKey="iCounselingApp.EducationDegree.BACHELOR_DEGREE" />
                    </option>
                    <option value="DOCOTRAL_DEGREE">
                      <Translate contentKey="iCounselingApp.EducationDegree.DOCOTRAL_DEGREE" />
                    </option>
                    <option value="MASTER_DEGREE">
                      <Translate contentKey="iCounselingApp.EducationDegree.MASTER_DEGREE" />
                    </option>
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/education" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  counselors: storeState.counselor.entities,
  visitors: storeState.visitor.entities,
  educationEntity: storeState.education.entity,
  loading: storeState.education.loading,
  updating: storeState.education.updating,
  updateSuccess: storeState.education.updateSuccess
});

const mapDispatchToProps = {
  getCounselors,
  getVisitors,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(EducationUpdate);
