// src/main/webapp/app/entities/counseling-case/counseling-case-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './counseling-case.reducer';
import { ICounselingCase } from 'app/shared/model/counseling-case.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ICounselingCaseDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class CounselingCaseDetail extends React.Component<ICounselingCaseDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { counselingCaseEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="iCounselingApp.counselingCase.detail.title">CounselingCase</Translate> [<b>{counselingCaseEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="status">
                <Translate contentKey="iCounselingApp.counselingCase.status">Status</Translate>
              </span>
            </dt>
            <dd>{counselingCaseEntity.status}</dd>
            <dt>
              <Translate contentKey="iCounselingApp.counselingCase.visitor">Visitor</Translate>
            </dt>
            <dd>{counselingCaseEntity.visitorId ? counselingCaseEntity.visitorId : ''}</dd>
            <dt>
              <Translate contentKey="iCounselingApp.counselingCase.counselor">Counselor</Translate>
            </dt>
            <dd>{counselingCaseEntity.counselorId ? counselingCaseEntity.counselorId : ''}</dd>
          </dl>
          <Button tag={Link} to="/entity/counseling-case" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/counseling-case/${counselingCaseEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ counselingCase }: IRootState) => ({
  counselingCaseEntity: counselingCase.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CounselingCaseDetail);

// src/main/webapp/app/entities/counseling-case/counseling-case-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ICounselingCase } from 'app/shared/model/counseling-case.model';

@Component({
  selector: 'jhi-counseling-case-detail',
  templateUrl: './counseling-case-detail.component.html'
})
export class CounselingCaseDetailComponent implements OnInit {
  counselingCase: ICounselingCase;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.data.subscribe(({ counselingCase }) => {
      this.counselingCase = counselingCase;
    });
  }

  previousState() {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="counselingCase">
            <h2><span jhiTranslate="iCounselingApp.counselingCase.detail.title">Counseling Case</span> {{counselingCase.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="iCounselingApp.counselingCase.status">Status</span></dt>
                <dd>
                    <span jhiTranslate="{{'iCounselingApp.CounselingCaseStatus.' + counselingCase.status}}">{{counselingCase.status}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.counselingCase.visitor">Visitor</span></dt>
                <dd>
                    <div *ngIf="counselingCase.visitorId">
                        <a [routerLink]="['/visitor', counselingCase.visitorId, 'view']">{{counselingCase.visitorId}}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.counselingCase.counselor">Counselor</span></dt>
                <dd>
                    <div *ngIf="counselingCase.counselorId">
                        <a [routerLink]="['/counselor', counselingCase.counselorId, 'view']">{{counselingCase.counselorId}}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/counseling-case', counselingCase.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>
