// src/main/webapp/app/entities/counseling-case/counseling-case-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { ICounselingCase, CounselingCase } from 'app/shared/model/counseling-case.model';
import { CounselingCaseService } from './counseling-case.service';
import { IVisitor } from 'app/shared/model/visitor.model';
import { VisitorService } from 'app/entities/visitor';
import { ICounselor } from 'app/shared/model/counselor.model';
import { CounselorService } from 'app/entities/counselor';

@Component({
  selector: 'jhi-counseling-case-update',
  templateUrl: './counseling-case-update.component.html'
})
export class CounselingCaseUpdateComponent implements OnInit {
  isSaving: boolean;

  visitors: IVisitor[];

  counselors: ICounselor[];

  editForm = this.fb.group({
    id: [],
    status: [null, [Validators.required]],
    visitorId: [],
    counselorId: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected counselingCaseService: CounselingCaseService,
    protected visitorService: VisitorService,
    protected counselorService: CounselorService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ counselingCase }) => {
      this.updateForm(counselingCase);
    });
    this.visitorService
      .query({ filter: 'counselingcase-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<IVisitor[]>) => mayBeOk.ok),
        map((response: HttpResponse<IVisitor[]>) => response.body)
      )
      .subscribe(
        (res: IVisitor[]) => {
          if (!this.editForm.get('visitorId').value) {
            this.visitors = res;
          } else {
            this.visitorService
              .find(this.editForm.get('visitorId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<IVisitor>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<IVisitor>) => subResponse.body)
              )
              .subscribe(
                (subRes: IVisitor) => (this.visitors = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.counselorService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICounselor[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICounselor[]>) => response.body)
      )
      .subscribe((res: ICounselor[]) => (this.counselors = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(counselingCase: ICounselingCase) {
    this.editForm.patchValue({
      id: counselingCase.id,
      status: counselingCase.status,
      visitorId: counselingCase.visitorId,
      counselorId: counselingCase.counselorId
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const counselingCase = this.createFromForm();
    if (counselingCase.id !== undefined) {
      this.subscribeToSaveResponse(this.counselingCaseService.update(counselingCase));
    } else {
      this.subscribeToSaveResponse(this.counselingCaseService.create(counselingCase));
    }
  }

  private createFromForm(): ICounselingCase {
    return {
      ...new CounselingCase(),
      id: this.editForm.get(['id']).value,
      status: this.editForm.get(['status']).value,
      visitorId: this.editForm.get(['visitorId']).value,
      counselorId: this.editForm.get(['counselorId']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICounselingCase>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackVisitorById(index: number, item: IVisitor) {
    return item.id;
  }

  trackCounselorById(index: number, item: ICounselor) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-counseling-case-heading" jhiTranslate="iCounselingApp.counselingCase.home.createOrEditLabel">Create or edit a Counseling Case</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.counselingCase.status" for="field_status">Status</label>
                    <select class="form-control" name="status" formControlName="status" id="field_status">
                        <option value="OPENED">{{'iCounselingApp.CounselingCaseStatus.OPENED' | translate}}</option>
                        <option value="CLOSED">{{'iCounselingApp.CounselingCaseStatus.CLOSED' | translate}}</option>
                    </select>
                    <div *ngIf="editForm.get('status').invalid && (editForm.get('status').dirty || editForm.get('status').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('status').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.counselingCase.visitor" for="field_visitor">Visitor</label>
                    <select class="form-control" id="field_visitor" name="visitor" formControlName="visitorId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="visitorOption.id" *ngFor="let visitorOption of visitors; trackBy: trackVisitorById">{{visitorOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.counselingCase.counselor" for="field_counselor">Counselor</label>
                    <select class="form-control" id="field_counselor" name="counselor" formControlName="counselorId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="counselorOption.id" *ngFor="let counselorOption of counselors; trackBy: trackCounselorById">{{counselorOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/counseling-case/counseling-case-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IVisitor } from 'app/shared/model/visitor.model';
import { getEntities as getVisitors } from 'app/entities/visitor/visitor.reducer';
import { ICounselor } from 'app/shared/model/counselor.model';
import { getEntities as getCounselors } from 'app/entities/counselor/counselor.reducer';
import { getEntity, updateEntity, createEntity, reset } from './counseling-case.reducer';
import { ICounselingCase } from 'app/shared/model/counseling-case.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer, convertDateTimeToServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ICounselingCaseUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface ICounselingCaseUpdateState {
  isNew: boolean;
  visitorId: string;
  counselorId: string;
}

export class CounselingCaseUpdate extends React.Component<ICounselingCaseUpdateProps, ICounselingCaseUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      visitorId: '0',
      counselorId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getVisitors();
    this.props.getCounselors();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { counselingCaseEntity } = this.props;
      const entity = {
        ...counselingCaseEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/counseling-case');
  };

  render() {
    const { counselingCaseEntity, visitors, counselors, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="iCounselingApp.counselingCase.home.createOrEditLabel">
              <Translate contentKey="iCounselingApp.counselingCase.home.createOrEditLabel">Create or edit a CounselingCase</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : counselingCaseEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="counseling-case-id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="counseling-case-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="statusLabel" for="counseling-case-status">
                    <Translate contentKey="iCounselingApp.counselingCase.status">Status</Translate>
                  </Label>
                  <AvInput
                    id="counseling-case-status"
                    type="select"
                    className="form-control"
                    name="status"
                    value={(!isNew && counselingCaseEntity.status) || 'OPENED'}
                  >
                    <option value="OPENED">
                      <Translate contentKey="iCounselingApp.CounselingCaseStatus.OPENED" />
                    </option>
                    <option value="CLOSED">
                      <Translate contentKey="iCounselingApp.CounselingCaseStatus.CLOSED" />
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="counseling-case-visitor">
                    <Translate contentKey="iCounselingApp.counselingCase.visitor">Visitor</Translate>
                  </Label>
                  <AvInput id="counseling-case-visitor" type="select" className="form-control" name="visitorId">
                    <option value="" key="0" />
                    {visitors
                      ? visitors.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="counseling-case-counselor">
                    <Translate contentKey="iCounselingApp.counselingCase.counselor">Counselor</Translate>
                  </Label>
                  <AvInput id="counseling-case-counselor" type="select" className="form-control" name="counselorId">
                    <option value="" key="0" />
                    {counselors
                      ? counselors.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/counseling-case" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  visitors: storeState.visitor.entities,
  counselors: storeState.counselor.entities,
  counselingCaseEntity: storeState.counselingCase.entity,
  loading: storeState.counselingCase.loading,
  updating: storeState.counselingCase.updating,
  updateSuccess: storeState.counselingCase.updateSuccess
});

const mapDispatchToProps = {
  getVisitors,
  getCounselors,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CounselingCaseUpdate);
