// src/main/webapp/app/entities/task/task-update.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpErrorResponse, HttpResponse} from '@angular/common/http';
import {FormBuilder, Validators} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {JhiAlertService} from 'ng-jhipster';
import {ITask, Task} from 'app/shared/model/task.model';
import {TaskService} from './task.service';
import {IReminder} from 'app/shared/model/reminder.model';
import {ReminderService} from 'app/entities/reminder';
import {ISchedule} from 'app/shared/model/schedule.model';
import {ScheduleService} from 'app/entities/schedule';
import {IPlanning} from 'app/shared/model/planning.model';
import {PlanningService} from 'app/entities/planning';

@Component({
  selector: 'jhi-task-update',
  templateUrl: './task-update.component.html'
})
export class TaskUpdateComponent implements OnInit {
  isSaving: boolean;

  reminders: IReminder[];

  schedules: ISchedule[];

  plannings: IPlanning[];

  editForm = this.fb.group({
    id: [],
    repeatTime: [null, [Validators.required]],
    repeatUntil: [null, [Validators.required]],
    reminderId: [],
    scheduleId: [],
    planningId: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected taskService: TaskService,
    protected reminderService: ReminderService,
    protected scheduleService: ScheduleService,
    protected planningService: PlanningService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ task }) => {
      this.updateForm(task);
    });
    this.reminderService
      .query({ filter: 'task-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<IReminder[]>) => mayBeOk.ok),
        map((response: HttpResponse<IReminder[]>) => response.body)
      )
      .subscribe(
        (res: IReminder[]) => {
          if (!this.editForm.get('reminderId').value) {
            this.reminders = res;
          } else {
            this.reminderService
              .find(this.editForm.get('reminderId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<IReminder>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<IReminder>) => subResponse.body)
              )
              .subscribe(
                (subRes: IReminder) => (this.reminders = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.scheduleService
      .query({ filter: 'task-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<ISchedule[]>) => mayBeOk.ok),
        map((response: HttpResponse<ISchedule[]>) => response.body)
      )
      .subscribe(
        (res: ISchedule[]) => {
          if (!this.editForm.get('scheduleId').value) {
            this.schedules = res;
          } else {
            this.scheduleService
              .find(this.editForm.get('scheduleId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<ISchedule>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<ISchedule>) => subResponse.body)
              )
              .subscribe(
                (subRes: ISchedule) => (this.schedules = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.planningService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IPlanning[]>) => mayBeOk.ok),
        map((response: HttpResponse<IPlanning[]>) => response.body)
      )
      .subscribe((res: IPlanning[]) => (this.plannings = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(task: ITask) {
    this.editForm.patchValue({
      id: task.id,
      repeatTime: task.repeatTime,
      repeatUntil: task.repeatUntil,
      reminderId: task.reminderId,
      scheduleId: task.scheduleId,
      planningId: task.planningId
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const task = this.createFromForm();
    if (task.id !== undefined) {
      this.subscribeToSaveResponse(this.taskService.update(task));
    } else {
      this.subscribeToSaveResponse(this.taskService.create(task));
    }
  }

  private createFromForm(): ITask {
    return {
      ...new Task(),
      id: this.editForm.get(['id']).value,
      repeatTime: this.editForm.get(['repeatTime']).value,
      repeatUntil: this.editForm.get(['repeatUntil']).value,
      reminderId: this.editForm.get(['reminderId']).value,
      scheduleId: this.editForm.get(['scheduleId']).value,
      planningId: this.editForm.get(['planningId']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ITask>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackReminderById(index: number, item: IReminder) {
    return item.id;
  }

  trackScheduleById(index: number, item: ISchedule) {
    return item.id;
  }

  trackPlanningById(index: number, item: IPlanning) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-task-heading" jhiTranslate="iCounselingApp.task.home.createOrEditLabel">Create or edit a Task</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.task.repeatTime" for="field_repeatTime">Repeat Time</label>
                    <select class="form-control" name="repeatTime" formControlName="repeatTime" id="field_repeatTime">
                        <option value="NONE">{{'iCounselingApp.RepeatTime.NONE' | translate}}</option>
                        <option value="DAILY">{{'iCounselingApp.RepeatTime.DAILY' | translate}}</option>
                        <option value="WEEKLY">{{'iCounselingApp.RepeatTime.WEEKLY' | translate}}</option>
                        <option value="MONTHLY">{{'iCounselingApp.RepeatTime.MONTHLY' | translate}}</option>
                        <option value="YEARLY">{{'iCounselingApp.RepeatTime.YEARLY' | translate}}</option>
                    </select>
                    <div *ngIf="editForm.get('repeatTime').invalid && (editForm.get('repeatTime').dirty || editForm.get('repeatTime').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('repeatTime').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.task.repeatUntil" for="field_repeatUntil">Repeat Until</label>
                    <select class="form-control" name="repeatUntil" formControlName="repeatUntil" id="field_repeatUntil">
                        <option value="NO_END_DATE">{{'iCounselingApp.RepeatUntil.NO_END_DATE' | translate}}</option>
                        <option value="SET_END_DATE">{{'iCounselingApp.RepeatUntil.SET_END_DATE' | translate}}</option>
                        <option value="SET_NUMBER_OF_TIMES">{{'iCounselingApp.RepeatUntil.SET_NUMBER_OF_TIMES' | translate}}</option>
                    </select>
                    <div *ngIf="editForm.get('repeatUntil').invalid && (editForm.get('repeatUntil').dirty || editForm.get('repeatUntil').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('repeatUntil').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.task.reminder" for="field_reminder">Reminder</label>
                    <select class="form-control" id="field_reminder" name="reminder" formControlName="reminderId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="reminderOption.id" *ngFor="let reminderOption of reminders; trackBy: trackReminderById">{{reminderOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.task.schedule" for="field_schedule">Schedule</label>
                    <select class="form-control" id="field_schedule" name="schedule" formControlName="scheduleId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="scheduleOption.id" *ngFor="let scheduleOption of schedules; trackBy: trackScheduleById">{{scheduleOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.task.planning" for="field_planning">Planning</label>
                    <select class="form-control" id="field_planning" name="planning" formControlName="planningId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="planningOption.id" *ngFor="let planningOption of plannings; trackBy: trackPlanningById">{{planningOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/task/task-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IReminder } from 'app/shared/model/reminder.model';
import { getEntities as getReminders } from 'app/entities/reminder/reminder.reducer';
import { ISchedule } from 'app/shared/model/schedule.model';
import { getEntities as getSchedules } from 'app/entities/schedule/schedule.reducer';
import { IPlanning } from 'app/shared/model/planning.model';
import { getEntities as getPlannings } from 'app/entities/planning/planning.reducer';
import { getEntity, updateEntity, createEntity, reset } from './task.reducer';
import { ITask } from 'app/shared/model/task.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer, convertDateTimeToServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ITaskUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface ITaskUpdateState {
  isNew: boolean;
  reminderId: string;
  scheduleId: string;
  planningId: string;
}

export class TaskUpdate extends React.Component<ITaskUpdateProps, ITaskUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      reminderId: '0',
      scheduleId: '0',
      planningId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getReminders();
    this.props.getSchedules();
    this.props.getPlannings();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { taskEntity } = this.props;
      const entity = {
        ...taskEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/task');
  };

  render() {
    const { taskEntity, reminders, schedules, plannings, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="iCounselingApp.task.home.createOrEditLabel">
              <Translate contentKey="iCounselingApp.task.home.createOrEditLabel">Create or edit a Task</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : taskEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="task-id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="task-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="repeatTimeLabel" for="task-repeatTime">
                    <Translate contentKey="iCounselingApp.task.repeatTime">Repeat Time</Translate>
                  </Label>
                  <AvInput
                    id="task-repeatTime"
                    type="select"
                    className="form-control"
                    name="repeatTime"
                    value={(!isNew && taskEntity.repeatTime) || 'NONE'}
                  >
                    <option value="NONE">
                      <Translate contentKey="iCounselingApp.RepeatTime.NONE" />
                    </option>
                    <option value="DAILY">
                      <Translate contentKey="iCounselingApp.RepeatTime.DAILY" />
                    </option>
                    <option value="WEEKLY">
                      <Translate contentKey="iCounselingApp.RepeatTime.WEEKLY" />
                    </option>
                    <option value="MONTHLY">
                      <Translate contentKey="iCounselingApp.RepeatTime.MONTHLY" />
                    </option>
                    <option value="YEARLY">
                      <Translate contentKey="iCounselingApp.RepeatTime.YEARLY" />
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label id="repeatUntilLabel" for="task-repeatUntil">
                    <Translate contentKey="iCounselingApp.task.repeatUntil">Repeat Until</Translate>
                  </Label>
                  <AvInput
                    id="task-repeatUntil"
                    type="select"
                    className="form-control"
                    name="repeatUntil"
                    value={(!isNew && taskEntity.repeatUntil) || 'NO_END_DATE'}
                  >
                    <option value="NO_END_DATE">
                      <Translate contentKey="iCounselingApp.RepeatUntil.NO_END_DATE" />
                    </option>
                    <option value="SET_END_DATE">
                      <Translate contentKey="iCounselingApp.RepeatUntil.SET_END_DATE" />
                    </option>
                    <option value="SET_NUMBER_OF_TIMES">
                      <Translate contentKey="iCounselingApp.RepeatUntil.SET_NUMBER_OF_TIMES" />
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="task-reminder">
                    <Translate contentKey="iCounselingApp.task.reminder">Reminder</Translate>
                  </Label>
                  <AvInput id="task-reminder" type="select" className="form-control" name="reminderId">
                    <option value="" key="0" />
                    {reminders
                      ? reminders.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="task-schedule">
                    <Translate contentKey="iCounselingApp.task.schedule">Schedule</Translate>
                  </Label>
                  <AvInput id="task-schedule" type="select" className="form-control" name="scheduleId">
                    <option value="" key="0" />
                    {schedules
                      ? schedules.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="task-planning">
                    <Translate contentKey="iCounselingApp.task.planning">Planning</Translate>
                  </Label>
                  <AvInput id="task-planning" type="select" className="form-control" name="planningId">
                    <option value="" key="0" />
                    {plannings
                      ? plannings.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/task" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  reminders: storeState.reminder.entities,
  schedules: storeState.schedule.entities,
  plannings: storeState.planning.entities,
  taskEntity: storeState.task.entity,
  loading: storeState.task.loading,
  updating: storeState.task.updating,
  updateSuccess: storeState.task.updateSuccess
});

const mapDispatchToProps = {
  getReminders,
  getSchedules,
  getPlannings,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(TaskUpdate);
