// src/main/webapp/app/entities/time-reserved/time-reserved-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ITimeReserved } from 'app/shared/model/time-reserved.model';

@Component({
  selector: 'jhi-time-reserved-detail',
  templateUrl: './time-reserved-detail.component.html'
})
export class TimeReservedDetailComponent implements OnInit {
  timeReserved: ITimeReserved;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.data.subscribe(({ timeReserved }) => {
      this.timeReserved = timeReserved;
    });
  }

  previousState() {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="timeReserved">
            <h2><span jhiTranslate="iCounselingApp.timeReserved.detail.title">Time Reserved</span> {{timeReserved.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="iCounselingApp.timeReserved.date">Date</span></dt>
                <dd>
                    <span>{{timeReserved.date}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.timeReserved.description">Description</span></dt>
                <dd>
                    <span>{{timeReserved.description}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.timeReserved.time">Time</span></dt>
                <dd>
                    <span>{{timeReserved.time}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.timeReserved.counselor">Counselor</span></dt>
                <dd>
                    <div *ngIf="timeReserved.counselorId">
                        <a [routerLink]="['/counselor', timeReserved.counselorId, 'view']">{{timeReserved.counselorId}}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/time-reserved', timeReserved.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/time-reserved/time-reserved-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './time-reserved.reducer';
import { ITimeReserved } from 'app/shared/model/time-reserved.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ITimeReservedDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class TimeReservedDetail extends React.Component<ITimeReservedDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { timeReservedEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="iCounselingApp.timeReserved.detail.title">TimeReserved</Translate> [<b>{timeReservedEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="dateTime">
                <Translate contentKey="iCounselingApp.timeReserved.dateTime">Date Time</Translate>
              </span>
            </dt>
            <dd>
              <TextFormat value={timeReservedEntity.dateTime} type="date" format={APP_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="description">
                <Translate contentKey="iCounselingApp.timeReserved.description">Description</Translate>
              </span>
            </dt>
            <dd>{timeReservedEntity.description}</dd>
            <dt>
              <Translate contentKey="iCounselingApp.timeReserved.counselor">Counselor</Translate>
            </dt>
            <dd>{timeReservedEntity.counselorId ? timeReservedEntity.counselorId : ''}</dd>
          </dl>
          <Button tag={Link} to="/entity/time-reserved" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/time-reserved/${timeReservedEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ timeReserved }: IRootState) => ({
  timeReservedEntity: timeReserved.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(TimeReservedDetail);
