// src/main/webapp/app/entities/score/score-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction, openFile, byteSize } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './score.reducer';
import { IScore } from 'app/shared/model/score.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IScoreDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class ScoreDetail extends React.Component<IScoreDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { scoreEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="iCounselingApp.score.detail.title">Score</Translate> [<b>{scoreEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="total">
                <Translate contentKey="iCounselingApp.score.total">Total</Translate>
              </span>
            </dt>
            <dd>{scoreEntity.total}</dd>
            <dt>
              <span id="image">
                <Translate contentKey="iCounselingApp.score.image">Image</Translate>
              </span>
            </dt>
            <dd>
              {scoreEntity.image ? (
                <div>
                  <a onClick={openFile(scoreEntity.imageContentType, scoreEntity.image)}>
                    <Translate contentKey="entity.action.open">Open</Translate>&nbsp;
                  </a>
                  <span>
                    {scoreEntity.imageContentType}, {byteSize(scoreEntity.image)}
                  </span>
                </div>
              ) : null}
            </dd>
            <dt>
              <span id="degree">
                <Translate contentKey="iCounselingApp.score.degree">Degree</Translate>
              </span>
            </dt>
            <dd>{scoreEntity.degree}</dd>
          </dl>
          <Button tag={Link} to="/entity/score" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/score/${scoreEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ score }: IRootState) => ({
  scoreEntity: score.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ScoreDetail);

// src/main/webapp/app/entities/score/score-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { JhiDataUtils } from 'ng-jhipster';

import { IScore } from 'app/shared/model/score.model';

@Component({
  selector: 'jhi-score-detail',
  templateUrl: './score-detail.component.html'
})
export class ScoreDetailComponent implements OnInit {
  score: IScore;

  constructor(protected dataUtils: JhiDataUtils, protected activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.data.subscribe(({ score }) => {
      this.score = score;
    });
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }
  previousState() {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="score">
            <h2><span jhiTranslate="iCounselingApp.score.detail.title">Score</span> {{score.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="iCounselingApp.score.total">Total</span></dt>
                <dd>
                    <span>{{score.total}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.score.image">Image</span></dt>
                <dd>
                    <div *ngIf="score.image">
                        <a (click)="openFile(score.imageContentType, score.image)" jhiTranslate="entity.action.open">open</a>
                        {{score.imageContentType}}, {{byteSize(score.image)}}
                    </div>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.score.degree">Degree</span></dt>
                <dd>
                    <span jhiTranslate="{{'iCounselingApp.ScoreDegree.' + score.degree}}">{{score.degree}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/score', score.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>
