// src/main/webapp/app/entities/visitor/visitor-update.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpErrorResponse, HttpResponse} from '@angular/common/http';
import {FormBuilder} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {JhiAlertService} from 'ng-jhipster';
import {IVisitor, Visitor} from 'app/shared/model/visitor.model';
import {VisitorService} from './visitor.service';
import {IScore} from 'app/shared/model/score.model';
import {ScoreService} from 'app/entities/score';
import {IEducation} from 'app/shared/model/education.model';
import {EducationService} from 'app/entities/education';
import {IUser, UserService} from 'app/core';
import {ICounselingCase} from 'app/shared/model/counseling-case.model';
import {CounselingCaseService} from 'app/entities/counseling-case';
import {ILibrary} from 'app/shared/model/library.model';
import {LibraryService} from 'app/entities/library';

@Component({
  selector: 'jhi-visitor-update',
  templateUrl: './visitor-update.component.html'
})
export class VisitorUpdateComponent implements OnInit {
  isSaving: boolean;

  scores: IScore[];

  educations: IEducation[];

  users: IUser[];

  counselingcases: ICounselingCase[];

  libraries: ILibrary[];

  editForm = this.fb.group({
    id: [],
    scoreId: [],
    educationId: [],
    userId: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected visitorService: VisitorService,
    protected scoreService: ScoreService,
    protected educationService: EducationService,
    protected userService: UserService,
    protected counselingCaseService: CounselingCaseService,
    protected libraryService: LibraryService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ visitor }) => {
      this.updateForm(visitor);
    });
    this.scoreService
      .query({ filter: 'visitor-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<IScore[]>) => mayBeOk.ok),
        map((response: HttpResponse<IScore[]>) => response.body)
      )
      .subscribe(
        (res: IScore[]) => {
          if (!this.editForm.get('scoreId').value) {
            this.scores = res;
          } else {
            this.scoreService
              .find(this.editForm.get('scoreId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<IScore>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<IScore>) => subResponse.body)
              )
              .subscribe(
                (subRes: IScore) => (this.scores = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.educationService
      .query({ filter: 'visitor-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<IEducation[]>) => mayBeOk.ok),
        map((response: HttpResponse<IEducation[]>) => response.body)
      )
      .subscribe(
        (res: IEducation[]) => {
          if (!this.editForm.get('educationId').value) {
            this.educations = res;
          } else {
            this.educationService
              .find(this.editForm.get('educationId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<IEducation>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<IEducation>) => subResponse.body)
              )
              .subscribe(
                (subRes: IEducation) => (this.educations = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.userService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IUser[]>) => mayBeOk.ok),
        map((response: HttpResponse<IUser[]>) => response.body)
      )
      .subscribe((res: IUser[]) => (this.users = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.counselingCaseService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICounselingCase[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICounselingCase[]>) => response.body)
      )
      .subscribe((res: ICounselingCase[]) => (this.counselingcases = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.libraryService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ILibrary[]>) => mayBeOk.ok),
        map((response: HttpResponse<ILibrary[]>) => response.body)
      )
      .subscribe((res: ILibrary[]) => (this.libraries = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(visitor: IVisitor) {
    this.editForm.patchValue({
      id: visitor.id,
      scoreId: visitor.scoreId,
      educationId: visitor.educationId,
      userId: visitor.userId
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const visitor = this.createFromForm();
    if (visitor.id !== undefined) {
      this.subscribeToSaveResponse(this.visitorService.update(visitor));
    } else {
      this.subscribeToSaveResponse(this.visitorService.create(visitor));
    }
  }

  private createFromForm(): IVisitor {
    return {
      ...new Visitor(),
      id: this.editForm.get(['id']).value,
      scoreId: this.editForm.get(['scoreId']).value,
      educationId: this.editForm.get(['educationId']).value,
      userId: this.editForm.get(['userId']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IVisitor>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackScoreById(index: number, item: IScore) {
    return item.id;
  }

  trackEducationById(index: number, item: IEducation) {
    return item.id;
  }

  trackUserById(index: number, item: IUser) {
    return item.id;
  }

  trackCounselingCaseById(index: number, item: ICounselingCase) {
    return item.id;
  }

  trackLibraryById(index: number, item: ILibrary) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-visitor-heading" jhiTranslate="iCounselingApp.visitor.home.createOrEditLabel">Create or edit a Visitor</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                           readonly/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.visitor.score" for="field_score">Score</label>
                    <select class="form-control" id="field_score" name="score" formControlName="scoreId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="scoreOption.id" *ngFor="let scoreOption of scores; trackBy: trackScoreById">{{scoreOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.visitor.education" for="field_education">Education</label>
                    <select class="form-control" id="field_education" name="education" formControlName="educationId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="educationOption.id" *ngFor="let educationOption of educations; trackBy: trackEducationById">{{educationOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.visitor.user"
                           for="field_user">User</label>
                    <select class="form-control" id="field_user" name="user" formControlName="userId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="userOption.id"
                                *ngFor="let userOption of users; trackBy: trackUserById">{{userOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/visitor/visitor-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IScore } from 'app/shared/model/score.model';
import { getEntities as getScores } from 'app/entities/score/score.reducer';
import { IEducation } from 'app/shared/model/education.model';
import { getEntities as getEducations } from 'app/entities/education/education.reducer';
import { IUser } from 'app/shared/model/user.model';
import { getUsers } from 'app/modules/administration/user-management/user-management.reducer';
import { ICounselingCase } from 'app/shared/model/counseling-case.model';
import { getEntities as getCounselingCases } from 'app/entities/counseling-case/counseling-case.reducer';
import { ILibrary } from 'app/shared/model/library.model';
import { getEntities as getLibraries } from 'app/entities/library/library.reducer';
import { getEntity, updateEntity, createEntity, reset } from './visitor.reducer';
import { IVisitor } from 'app/shared/model/visitor.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer, convertDateTimeToServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IVisitorUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface IVisitorUpdateState {
  isNew: boolean;
  scoreId: string;
  educationId: string;
  userId: string;
  counselingCaseId: string;
  libraryId: string;
}

export class VisitorUpdate extends React.Component<IVisitorUpdateProps, IVisitorUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      scoreId: '0',
      educationId: '0',
      userId: '0',
      counselingCaseId: '0',
      libraryId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getScores();
    this.props.getEducations();
    this.props.getUsers();
    this.props.getCounselingCases();
    this.props.getLibraries();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { visitorEntity } = this.props;
      const entity = {
        ...visitorEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/visitor');
  };

  render() {
    const { visitorEntity, scores, educations, users, counselingCases, libraries, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="iCounselingApp.visitor.home.createOrEditLabel">
              <Translate contentKey="iCounselingApp.visitor.home.createOrEditLabel">Create or edit a Visitor</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : visitorEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="visitor-id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="visitor-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label for="visitor-score">
                    <Translate contentKey="iCounselingApp.visitor.score">Score</Translate>
                  </Label>
                  <AvInput id="visitor-score" type="select" className="form-control" name="scoreId">
                    <option value="" key="0" />
                    {scores
                      ? scores.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="visitor-education">
                    <Translate contentKey="iCounselingApp.visitor.education">Education</Translate>
                  </Label>
                  <AvInput id="visitor-education" type="select" className="form-control" name="educationId">
                    <option value="" key="0" />
                    {educations
                      ? educations.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="visitor-user">
                    <Translate contentKey="iCounselingApp.visitor.user">User</Translate>
                  </Label>
                  <AvInput id="visitor-user" type="select" className="form-control" name="userId">
                    <option value="" key="0" />
                    {users
                      ? users.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/visitor" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  scores: storeState.score.entities,
  educations: storeState.education.entities,
  users: storeState.userManagement.users,
  counselingCases: storeState.counselingCase.entities,
  libraries: storeState.library.entities,
  visitorEntity: storeState.visitor.entity,
  loading: storeState.visitor.loading,
  updating: storeState.visitor.updating,
  updateSuccess: storeState.visitor.updateSuccess
});

const mapDispatchToProps = {
  getScores,
  getEducations,
  getUsers,
  getCounselingCases,
  getLibraries,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(VisitorUpdate);
