// src/main/webapp/app/entities/visitor/visitor-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IVisitor } from 'app/shared/model/visitor.model';

@Component({
  selector: 'jhi-visitor-detail',
  templateUrl: './visitor-detail.component.html'
})
export class VisitorDetailComponent implements OnInit {
  visitor: IVisitor;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.data.subscribe(({ visitor }) => {
      this.visitor = visitor;
    });
  }

  previousState() {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="visitor">
            <h2><span jhiTranslate="iCounselingApp.visitor.detail.title">Visitor</span> {{visitor.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="iCounselingApp.visitor.score">Score</span></dt>
                <dd>
                    <div *ngIf="visitor.scoreId">
                        <a [routerLink]="['/score', visitor.scoreId, 'view']">{{visitor.scoreId}}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.visitor.education">Education</span></dt>
                <dd>
                    <div *ngIf="visitor.educationId">
                        <a [routerLink]="['/education', visitor.educationId, 'view']">{{visitor.educationId}}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/visitor', visitor.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/visitor/visitor-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './visitor.reducer';
import { IVisitor } from 'app/shared/model/visitor.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IVisitorDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class VisitorDetail extends React.Component<IVisitorDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { visitorEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="iCounselingApp.visitor.detail.title">Visitor</Translate> [<b>{visitorEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <Translate contentKey="iCounselingApp.visitor.score">Score</Translate>
            </dt>
            <dd>{visitorEntity.scoreId ? visitorEntity.scoreId : ''}</dd>
            <dt>
              <Translate contentKey="iCounselingApp.visitor.education">Education</Translate>
            </dt>
            <dd>{visitorEntity.educationId ? visitorEntity.educationId : ''}</dd>
            <dt>
              <Translate contentKey="iCounselingApp.visitor.user">User</Translate>
            </dt>
            <dd>{visitorEntity.userId ? visitorEntity.userId : ''}</dd>
          </dl>
          <Button tag={Link} to="/entity/visitor" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/visitor/${visitorEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ visitor }: IRootState) => ({
  visitorEntity: visitor.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(VisitorDetail);
