// src/main/webapp/app/entities/reseume/reseume-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IReseume } from 'app/shared/model/reseume.model';

@Component({
  selector: 'jhi-reseume-detail',
  templateUrl: './reseume-detail.component.html'
})
export class ReseumeDetailComponent implements OnInit {
  reseume: IReseume;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.data.subscribe(({ reseume }) => {
      this.reseume = reseume;
    });
  }

  previousState() {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="reseume">
            <h2><span jhiTranslate="iCounselingApp.reseume.detail.title">Reseume</span> {{reseume.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="iCounselingApp.reseume.education">Education</span></dt>
                <dd>
                    <div *ngIf="reseume.educationId">
                        <a [routerLink]="['/education', reseume.educationId, 'view']">{{reseume.educationId}}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/reseume', reseume.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/reseume/reseume-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './reseume.reducer';
import { IReseume } from 'app/shared/model/reseume.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IReseumeDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class ReseumeDetail extends React.Component<IReseumeDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { reseumeEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="iCounselingApp.reseume.detail.title">Reseume</Translate> [<b>{reseumeEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <Translate contentKey="iCounselingApp.reseume.education">Education</Translate>
            </dt>
            <dd>{reseumeEntity.educationId ? reseumeEntity.educationId : ''}</dd>
          </dl>
          <Button tag={Link} to="/entity/reseume" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/reseume/${reseumeEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ reseume }: IRootState) => ({
  reseumeEntity: reseume.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ReseumeDetail);
