// src/main/webapp/app/entities/post/post-update.tsx
import React from 'react';
import {connect} from 'react-redux';
import {Link, RouteComponentProps} from 'react-router-dom';
import {Button, Col, Label, Row} from 'reactstrap';
import {AvForm, AvGroup, AvInput} from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import {byteSize, openFile, setFileData, translate, Translate} from 'react-jhipster';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {IRootState} from 'app/shared/reducers';
import {getEntities as getSchedules} from 'app/entities/schedule/schedule.reducer';
import {getEntities as getCounselors} from 'app/entities/counselor/counselor.reducer';
import {createEntity, getEntity, reset, setBlob, updateEntity} from './post.reducer';

// tslint:disable-next-line:no-unused-variable

export interface IPostUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {
}

export interface IPostUpdateState {
  isNew: boolean;
  scheduleId: string;
  counselorId: string;
}

export class PostUpdate extends React.Component<IPostUpdateProps, IPostUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      scheduleId: '0',
      counselorId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getSchedules();
    this.props.getCounselors();
  }

  onBlobChange = (isAnImage, name) => event => {
    setFileData(event, (contentType, data) => this.props.setBlob(name, data, contentType), isAnImage);
  };

  clearBlob = name => () => {
    this.props.setBlob(name, undefined, undefined);
  };

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const {postEntity} = this.props;
      const entity = {
        ...postEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/post');
  };

  render() {
    const {postEntity, schedules, counselors, loading, updating} = this.props;
    const {isNew} = this.state;

    const {image, imageContentType} = postEntity;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="iCounselingApp.post.home.createOrEditLabel">
              <Translate contentKey="iCounselingApp.post.home.createOrEditLabel">Create or edit a Post</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : postEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="post-id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="post-id" type="text" className="form-control" name="id" required readOnly/>
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <AvGroup>
                    <Label id="imageLabel" for="image">
                      <Translate contentKey="iCounselingApp.post.image">Image</Translate>
                    </Label>
                    <br/>
                    {image ? (
                      <div>
                        <a onClick={openFile(imageContentType, image)}>
                          <Translate contentKey="entity.action.open">Open</Translate>
                        </a>
                        <br/>
                        <Row>
                          <Col md="11">
                            <span>
                              {imageContentType}, {byteSize(image)}
                            </span>
                          </Col>
                          <Col md="1">
                            <Button color="danger" onClick={this.clearBlob('image')}>
                              <FontAwesomeIcon icon="times-circle"/>
                            </Button>
                          </Col>
                        </Row>
                      </div>
                    ) : null}
                    <input id="file_image" type="file" onChange={this.onBlobChange(false, 'image')}/>
                    <AvInput
                      type="hidden"
                      name="image"
                      value={image}
                      validate={{
                        required: {value: true, errorMessage: translate('entity.validation.required')}
                      }}
                    />
                  </AvGroup>
                </AvGroup>
                <AvGroup>
                  <Label id="documentFormatLabel" for="post-documentFormat">
                    <Translate contentKey="iCounselingApp.post.documentFormat">Document Format</Translate>
                  </Label>
                  <AvInput
                    id="post-documentFormat"
                    type="select"
                    className="form-control"
                    name="documentFormat"
                    value={(!isNew && postEntity.documentFormat) || 'PDF'}
                  >
                    <option value="PDF">
                      <Translate contentKey="iCounselingApp.DocumentFormat.PDF"/>
                    </option>
                    <option value="DOCX">
                      <Translate contentKey="iCounselingApp.DocumentFormat.DOCX"/>
                    </option>
                    <option value="DOC">
                      <Translate contentKey="iCounselingApp.DocumentFormat.DOC"/>
                    </option>
                    <option value="XLSX">
                      <Translate contentKey="iCounselingApp.DocumentFormat.XLSX"/>
                    </option>
                    <option value="PPT">
                      <Translate contentKey="iCounselingApp.DocumentFormat.PPT"/>
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="post-schedule">
                    <Translate contentKey="iCounselingApp.post.schedule">Schedule</Translate>
                  </Label>
                  <AvInput id="post-schedule" type="select" className="form-control" name="scheduleId">
                    <option value="" key="0"/>
                    {schedules
                      ? schedules.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="post-counselor">
                    <Translate contentKey="iCounselingApp.post.counselor">Counselor</Translate>
                  </Label>
                  <AvInput id="post-counselor" type="select" className="form-control" name="counselorId">
                    <option value="" key="0"/>
                    {counselors
                      ? counselors.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/post" replace color="info">
                  <FontAwesomeIcon icon="arrow-left"/>
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save"/>
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  schedules: storeState.schedule.entities,
  counselors: storeState.counselor.entities,
  postEntity: storeState.post.entity,
  loading: storeState.post.loading,
  updating: storeState.post.updating,
  updateSuccess: storeState.post.updateSuccess
});

const mapDispatchToProps = {
  getSchedules,
  getCounselors,
  getEntity,
  updateEntity,
  setBlob,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(PostUpdate);

// src/main/webapp/app/entities/post/post-update.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpErrorResponse, HttpResponse} from '@angular/common/http';
import {FormBuilder, Validators} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {JhiAlertService, JhiDataUtils} from 'ng-jhipster';
import {IPost, Post} from 'app/shared/model/post.model';
import {PostService} from './post.service';
import {ISchedule} from 'app/shared/model/schedule.model';
import {ScheduleService} from 'app/entities/schedule';
import {ICounselor} from 'app/shared/model/counselor.model';
import {CounselorService} from 'app/entities/counselor';

@Component({
  selector: 'jhi-post-update',
  templateUrl: './post-update.component.html'
})
export class PostUpdateComponent implements OnInit {
  isSaving: boolean;

  schedules: ISchedule[];

  counselors: ICounselor[];

  editForm = this.fb.group({
    id: [],
    image: [null, [Validators.required]],
    imageContentType: [],
    documentFormat: [null, [Validators.required]],
    scheduleId: [],
    counselorId: []
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected jhiAlertService: JhiAlertService,
    protected postService: PostService,
    protected scheduleService: ScheduleService,
    protected counselorService: CounselorService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ post }) => {
      this.updateForm(post);
    });
    this.scheduleService
      .query({ filter: 'post-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<ISchedule[]>) => mayBeOk.ok),
        map((response: HttpResponse<ISchedule[]>) => response.body)
      )
      .subscribe(
        (res: ISchedule[]) => {
          if (!this.editForm.get('scheduleId').value) {
            this.schedules = res;
          } else {
            this.scheduleService
              .find(this.editForm.get('scheduleId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<ISchedule>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<ISchedule>) => subResponse.body)
              )
              .subscribe(
                (subRes: ISchedule) => (this.schedules = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.counselorService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICounselor[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICounselor[]>) => response.body)
      )
      .subscribe((res: ICounselor[]) => (this.counselors = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(post: IPost) {
    this.editForm.patchValue({
      id: post.id,
      image: post.image,
      imageContentType: post.imageContentType,
      documentFormat: post.documentFormat,
      scheduleId: post.scheduleId,
      counselorId: post.counselorId
    });
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }

  setFileData(event, field: string, isImage) {
    return new Promise((resolve, reject) => {
      if (event && event.target && event.target.files && event.target.files[0]) {
        const file = event.target.files[0];
        if (isImage && !/^image\//.test(file.type)) {
          reject(`File was expected to be an image but was found to be ${file.type}`);
        } else {
          const filedContentType: string = field + 'ContentType';
          this.dataUtils.toBase64(file, base64Data => {
            this.editForm.patchValue({
              [field]: base64Data,
              [filedContentType]: file.type
            });
          });
        }
      } else {
        reject(`Base64 data was not set as file could not be extracted from passed parameter: ${event}`);
      }
    }).then(
      () => console.log('blob added'), // sucess
      this.onError
    );
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const post = this.createFromForm();
    if (post.id !== undefined) {
      this.subscribeToSaveResponse(this.postService.update(post));
    } else {
      this.subscribeToSaveResponse(this.postService.create(post));
    }
  }

  private createFromForm(): IPost {
    return {
      ...new Post(),
      id: this.editForm.get(['id']).value,
      imageContentType: this.editForm.get(['imageContentType']).value,
      image: this.editForm.get(['image']).value,
      documentFormat: this.editForm.get(['documentFormat']).value,
      scheduleId: this.editForm.get(['scheduleId']).value,
      counselorId: this.editForm.get(['counselorId']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IPost>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackScheduleById(index: number, item: ISchedule) {
    return item.id;
  }

  trackCounselorById(index: number, item: ICounselor) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-post-heading" jhiTranslate="iCounselingApp.post.home.createOrEditLabel">Create or edit a Post</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.post.image" for="field_image">Image</label>
                    <div>
                        <div *ngIf="editForm.get('image').value" class="form-text text-danger clearfix">
                            <a class="pull-left" (click)="openFile(editForm.get('imageContentType').value, editForm.get('image').value)" jhiTranslate="entity.action.open">open</a><br>
                            <span class="pull-left">{{editForm.get('imageContentType').value}}, {{byteSize(editForm.get('image').value)}}</span>
                            <button type="button" (click)="editForm.patchValue({image: null});editForm.patchValue({imageContentType: null});"
                                    class="btn btn-secondary btn-xs pull-right">
                                <fa-icon [icon]="'times'"></fa-icon>
                            </button>
                        </div>
                        <input type="file" id="file_image" (change)="setFileData($event, 'image', false)" jhiTranslate="entity.action.addblob"/>
                    </div>
                    <input type="hidden" class="form-control" name="image" id="field_image"
                           formControlName="image"/>
                    <input type="hidden" class="form-control" name="imageContentType" id="field_imageContentType"
                           formControlName="imageContentType" />
                    <div *ngIf="editForm.get('image').invalid && (editForm.get('image').dirty || editForm.get('image').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('image').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.post.documentFormat" for="field_documentFormat">Document Format</label>
                    <select class="form-control" name="documentFormat" formControlName="documentFormat" id="field_documentFormat">
                        <option value="PDF">{{'iCounselingApp.DocumentFormat.PDF' | translate}}</option>
                        <option value="DOCX">{{'iCounselingApp.DocumentFormat.DOCX' | translate}}</option>
                        <option value="DOC">{{'iCounselingApp.DocumentFormat.DOC' | translate}}</option>
                        <option value="XLSX">{{'iCounselingApp.DocumentFormat.XLSX' | translate}}</option>
                        <option value="PPT">{{'iCounselingApp.DocumentFormat.PPT' | translate}}</option>
                    </select>
                    <div *ngIf="editForm.get('documentFormat').invalid && (editForm.get('documentFormat').dirty || editForm.get('documentFormat').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('documentFormat').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.post.schedule" for="field_schedule">Schedule</label>
                    <select class="form-control" id="field_schedule" name="schedule" formControlName="scheduleId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="scheduleOption.id" *ngFor="let scheduleOption of schedules; trackBy: trackScheduleById">{{scheduleOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.post.counselor" for="field_counselor">Counselor</label>
                    <select class="form-control" id="field_counselor" name="counselor" formControlName="counselorId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="counselorOption.id" *ngFor="let counselorOption of counselors; trackBy: trackCounselorById">{{counselorOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
