// src/main/webapp/app/entities/document/document-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction, openFile, byteSize, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './document.reducer';
import { IDocument } from 'app/shared/model/document.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IDocumentDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class DocumentDetail extends React.Component<IDocumentDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { documentEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="iCounselingApp.document.detail.title">Document</Translate> [<b>{documentEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="title">
                <Translate contentKey="iCounselingApp.document.title">Title</Translate>
              </span>
            </dt>
            <dd>{documentEntity.title}</dd>
            <dt>
              <span id="description">
                <Translate contentKey="iCounselingApp.document.description">Description</Translate>
              </span>
            </dt>
            <dd>
              {documentEntity.description ? (
                <div>
                  <a onClick={openFile(documentEntity.descriptionContentType, documentEntity.description)}>
                    <Translate contentKey="entity.action.open">Open</Translate>&nbsp;
                  </a>
                  <span>
                    {documentEntity.descriptionContentType}, {byteSize(documentEntity.description)}
                  </span>
                </div>
              ) : null}
            </dd>
            <dt>
              <span id="price">
                <Translate contentKey="iCounselingApp.document.price">Price</Translate>
              </span>
            </dt>
            <dd>{documentEntity.price}</dd>
            <dt>
              <span id="publishedDate">
                <Translate contentKey="iCounselingApp.document.publishedDate">Published Date</Translate>
              </span>
            </dt>
            <dd>
              <TextFormat value={documentEntity.publishedDate} type="date" format={APP_LOCAL_DATE_FORMAT} />
            </dd>
            <dt>
              <span id="paymentType">
                <Translate contentKey="iCounselingApp.document.paymentType">Payment Type</Translate>
              </span>
            </dt>
            <dd>{documentEntity.paymentType}</dd>
            <dt>
              <span id="documentFormat">
                <Translate contentKey="iCounselingApp.document.documentFormat">Document Format</Translate>
              </span>
            </dt>
            <dd>{documentEntity.documentFormat}</dd>
            <dt>
              <span id="imagesGallery">
                <Translate contentKey="iCounselingApp.document.imagesGallery">Images Gallery</Translate>
              </span>
            </dt>
            <dd>
              {documentEntity.imagesGallery ? (
                <div>
                  <a onClick={openFile(documentEntity.imagesGalleryContentType, documentEntity.imagesGallery)}>
                    <Translate contentKey="entity.action.open">Open</Translate>&nbsp;
                  </a>
                  <span>
                    {documentEntity.imagesGalleryContentType}, {byteSize(documentEntity.imagesGallery)}
                  </span>
                </div>
              ) : null}
            </dd>
            <dt>
              <span id="tag">
                <Translate contentKey="iCounselingApp.document.tag">Tag</Translate>
              </span>
            </dt>
            <dd>{documentEntity.tag}</dd>
            <dt>
              <Translate contentKey="iCounselingApp.document.rate">Rate</Translate>
            </dt>
            <dd>{documentEntity.rateIndex ? documentEntity.rateIndex : ''}</dd>
            <dt>
              <Translate contentKey="iCounselingApp.document.comment">Comment</Translate>
            </dt>
            <dd>{documentEntity.commentId ? documentEntity.commentId : ''}</dd>
            <dt>
              <Translate contentKey="iCounselingApp.document.gategory">Gategory</Translate>
            </dt>
            <dd>{documentEntity.gategoryCategoryType ? documentEntity.gategoryCategoryType : ''}</dd>
            <dt>
              <Translate contentKey="iCounselingApp.document.counselor">Counselor</Translate>
            </dt>
            <dd>{documentEntity.counselorId ? documentEntity.counselorId : ''}</dd>
          </dl>
          <Button tag={Link} to="/entity/document" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/document/${documentEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ document }: IRootState) => ({
  documentEntity: document.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(DocumentDetail);

// src/main/webapp/app/entities/document/document-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { JhiDataUtils } from 'ng-jhipster';

import { IDocument } from 'app/shared/model/document.model';

@Component({
  selector: 'jhi-document-detail',
  templateUrl: './document-detail.component.html'
})
export class DocumentDetailComponent implements OnInit {
  document: IDocument;

  constructor(protected dataUtils: JhiDataUtils, protected activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.data.subscribe(({ document }) => {
      this.document = document;
    });
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }
  previousState() {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="document">
            <h2><span jhiTranslate="iCounselingApp.document.detail.title">Document</span> {{document.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="iCounselingApp.document.title">Title</span></dt>
                <dd>
                    <span>{{document.title}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.description">Description</span></dt>
                <dd>
                    <div *ngIf="document.description">
                        <a (click)="openFile(document.descriptionContentType, document.description)" jhiTranslate="entity.action.open">open</a>
                        {{document.descriptionContentType}}, {{byteSize(document.description)}}
                    </div>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.price">Price</span></dt>
                <dd>
                    <span>{{document.price}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.publishedDate">Published Date</span></dt>
                <dd>
                    <span>{{document.publishedDate}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.paymentType">Payment Type</span></dt>
                <dd>
                    <span jhiTranslate="{{'iCounselingApp.PaymentType.' + document.paymentType}}">{{document.paymentType}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.documentFormat">Document Format</span></dt>
                <dd>
                    <span jhiTranslate="{{'iCounselingApp.DocumentFormat.' + document.documentFormat}}">{{document.documentFormat}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.imagesGallery">Images Gallery</span></dt>
                <dd>
                    <div *ngIf="document.imagesGallery">
                        <a (click)="openFile(document.imagesGalleryContentType, document.imagesGallery)" jhiTranslate="entity.action.open">open</a>
                        {{document.imagesGalleryContentType}}, {{byteSize(document.imagesGallery)}}
                    </div>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.tag">Tag</span></dt>
                <dd>
                    <span>{{document.tag}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.rate">Rate</span></dt>
                <dd>
                    <div *ngIf="document.rateId">
                        <a [routerLink]="['/rate', document.rateId, 'view']">{{document.rateIndex}}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.comment">Comment</span></dt>
                <dd>
                    <div *ngIf="document.commentId">
                        <a [routerLink]="['/comment', document.commentId, 'view']">{{document.commentId}}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.gategory">Gategory</span></dt>
                <dd>
                    <div *ngIf="document.gategoryId">
                        <a [routerLink]="['/category', document.gategoryId, 'view']">{{document.gategoryCategoryType}}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.document.counselor">Counselor</span></dt>
                <dd>
                    <div *ngIf="document.counselorId">
                        <a [routerLink]="['/counselor', document.counselorId, 'view']">{{document.counselorId}}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/document', document.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>
