// src/main/webapp/app/entities/document/document-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, setFileData, openFile, byteSize, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IRate } from 'app/shared/model/rate.model';
import { getEntities as getRates } from 'app/entities/rate/rate.reducer';
import { IComment } from 'app/shared/model/comment.model';
import { getEntities as getComments } from 'app/entities/comment/comment.reducer';
import { ICategory } from 'app/shared/model/category.model';
import { getEntities as getCategories } from 'app/entities/category/category.reducer';
import { ICounselor } from 'app/shared/model/counselor.model';
import { getEntities as getCounselors } from 'app/entities/counselor/counselor.reducer';
import { getEntity, updateEntity, createEntity, setBlob, reset } from './document.reducer';
import { IDocument } from 'app/shared/model/document.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer, convertDateTimeToServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IDocumentUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface IDocumentUpdateState {
  isNew: boolean;
  rateId: string;
  commentId: string;
  gategoryId: string;
  counselorId: string;
}

export class DocumentUpdate extends React.Component<IDocumentUpdateProps, IDocumentUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      rateId: '0',
      commentId: '0',
      gategoryId: '0',
      counselorId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getRates();
    this.props.getComments();
    this.props.getCategories();
    this.props.getCounselors();
  }

  onBlobChange = (isAnImage, name) => event => {
    setFileData(event, (contentType, data) => this.props.setBlob(name, data, contentType), isAnImage);
  };

  clearBlob = name => () => {
    this.props.setBlob(name, undefined, undefined);
  };

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { documentEntity } = this.props;
      const entity = {
        ...documentEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/document');
  };

  render() {
    const { documentEntity, rates, comments, categories, counselors, loading, updating } = this.props;
    const { isNew } = this.state;

    const { description, descriptionContentType, imagesGallery, imagesGalleryContentType } = documentEntity;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="iCounselingApp.document.home.createOrEditLabel">
              <Translate contentKey="iCounselingApp.document.home.createOrEditLabel">Create or edit a Document</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : documentEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="document-id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="document-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="titleLabel" for="document-title">
                    <Translate contentKey="iCounselingApp.document.title">Title</Translate>
                  </Label>
                  <AvField
                    id="document-title"
                    type="text"
                    name="title"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <AvGroup>
                    <Label id="descriptionLabel" for="description">
                      <Translate contentKey="iCounselingApp.document.description">Description</Translate>
                    </Label>
                    <br />
                    {description ? (
                      <div>
                        <a onClick={openFile(descriptionContentType, description)}>
                          <Translate contentKey="entity.action.open">Open</Translate>
                        </a>
                        <br />
                        <Row>
                          <Col md="11">
                            <span>
                              {descriptionContentType}, {byteSize(description)}
                            </span>
                          </Col>
                          <Col md="1">
                            <Button color="danger" onClick={this.clearBlob('description')}>
                              <FontAwesomeIcon icon="times-circle" />
                            </Button>
                          </Col>
                        </Row>
                      </div>
                    ) : null}
                    <input id="file_description" type="file" onChange={this.onBlobChange(false, 'description')} />
                    <AvInput
                      type="hidden"
                      name="description"
                      value={description}
                      validate={{
                        required: { value: true, errorMessage: translate('entity.validation.required') }
                      }}
                    />
                  </AvGroup>
                </AvGroup>
                <AvGroup>
                  <Label id="priceLabel" for="document-price">
                    <Translate contentKey="iCounselingApp.document.price">Price</Translate>
                  </Label>
                  <AvField
                    id="document-price"
                    type="string"
                    className="form-control"
                    name="price"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      number: { value: true, errorMessage: translate('entity.validation.number') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="publishedDateLabel" for="document-publishedDate">
                    <Translate contentKey="iCounselingApp.document.publishedDate">Published Date</Translate>
                  </Label>
                  <AvField id="document-publishedDate" type="date" className="form-control" name="publishedDate" />
                </AvGroup>
                <AvGroup>
                  <Label id="paymentTypeLabel" for="document-paymentType">
                    <Translate contentKey="iCounselingApp.document.paymentType">Payment Type</Translate>
                  </Label>
                  <AvInput
                    id="document-paymentType"
                    type="select"
                    className="form-control"
                    name="paymentType"
                    value={(!isNew && documentEntity.paymentType) || 'FREE'}
                  >
                    <option value="FREE">
                      <Translate contentKey="iCounselingApp.PaymentType.FREE" />
                    </option>
                    <option value="PAID">
                      <Translate contentKey="iCounselingApp.PaymentType.PAID" />
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label id="documentFormatLabel" for="document-documentFormat">
                    <Translate contentKey="iCounselingApp.document.documentFormat">Document Format</Translate>
                  </Label>
                  <AvInput
                    id="document-documentFormat"
                    type="select"
                    className="form-control"
                    name="documentFormat"
                    value={(!isNew && documentEntity.documentFormat) || 'PDF'}
                  >
                    <option value="PDF">
                      <Translate contentKey="iCounselingApp.DocumentFormat.PDF" />
                    </option>
                    <option value="DOCX">
                      <Translate contentKey="iCounselingApp.DocumentFormat.DOCX" />
                    </option>
                    <option value="DOC">
                      <Translate contentKey="iCounselingApp.DocumentFormat.DOC" />
                    </option>
                    <option value="XLSX">
                      <Translate contentKey="iCounselingApp.DocumentFormat.XLSX" />
                    </option>
                    <option value="PPT">
                      <Translate contentKey="iCounselingApp.DocumentFormat.PPT" />
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <AvGroup>
                    <Label id="imagesGalleryLabel" for="imagesGallery">
                      <Translate contentKey="iCounselingApp.document.imagesGallery">Images Gallery</Translate>
                    </Label>
                    <br />
                    {imagesGallery ? (
                      <div>
                        <a onClick={openFile(imagesGalleryContentType, imagesGallery)}>
                          <Translate contentKey="entity.action.open">Open</Translate>
                        </a>
                        <br />
                        <Row>
                          <Col md="11">
                            <span>
                              {imagesGalleryContentType}, {byteSize(imagesGallery)}
                            </span>
                          </Col>
                          <Col md="1">
                            <Button color="danger" onClick={this.clearBlob('imagesGallery')}>
                              <FontAwesomeIcon icon="times-circle" />
                            </Button>
                          </Col>
                        </Row>
                      </div>
                    ) : null}
                    <input id="file_imagesGallery" type="file" onChange={this.onBlobChange(false, 'imagesGallery')} />
                    <AvInput
                      type="hidden"
                      name="imagesGallery"
                      value={imagesGallery}
                      validate={{
                        required: { value: true, errorMessage: translate('entity.validation.required') }
                      }}
                    />
                  </AvGroup>
                </AvGroup>
                <AvGroup>
                  <Label id="tagLabel" for="document-tag">
                    <Translate contentKey="iCounselingApp.document.tag">Tag</Translate>
                  </Label>
                  <AvField
                    id="document-tag"
                    type="text"
                    name="tag"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label for="document-rate">
                    <Translate contentKey="iCounselingApp.document.rate">Rate</Translate>
                  </Label>
                  <AvInput id="document-rate" type="select" className="form-control" name="rateId">
                    <option value="" key="0" />
                    {rates
                      ? rates.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.index}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="document-comment">
                    <Translate contentKey="iCounselingApp.document.comment">Comment</Translate>
                  </Label>
                  <AvInput id="document-comment" type="select" className="form-control" name="commentId">
                    <option value="" key="0" />
                    {comments
                      ? comments.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="document-gategory">
                    <Translate contentKey="iCounselingApp.document.gategory">Gategory</Translate>
                  </Label>
                  <AvInput id="document-gategory" type="select" className="form-control" name="gategoryId">
                    <option value="" key="0" />
                    {categories
                      ? categories.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.categoryType}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="document-counselor">
                    <Translate contentKey="iCounselingApp.document.counselor">Counselor</Translate>
                  </Label>
                  <AvInput id="document-counselor" type="select" className="form-control" name="counselorId">
                    <option value="" key="0" />
                    {counselors
                      ? counselors.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/document" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  rates: storeState.rate.entities,
  comments: storeState.comment.entities,
  categories: storeState.category.entities,
  counselors: storeState.counselor.entities,
  documentEntity: storeState.document.entity,
  loading: storeState.document.loading,
  updating: storeState.document.updating,
  updateSuccess: storeState.document.updateSuccess
});

const mapDispatchToProps = {
  getRates,
  getComments,
  getCategories,
  getCounselors,
  getEntity,
  updateEntity,
  setBlob,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(DocumentUpdate);

// src/main/webapp/app/entities/document/document-update.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpErrorResponse, HttpResponse} from '@angular/common/http';
import {FormBuilder, Validators} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {JhiAlertService, JhiDataUtils} from 'ng-jhipster';
import {Document, IDocument} from 'app/shared/model/document.model';
import {DocumentService} from './document.service';
import {IRate} from 'app/shared/model/rate.model';
import {RateService} from 'app/entities/rate';
import {IComment} from 'app/shared/model/comment.model';
import {CommentService} from 'app/entities/comment';
import {ICategory} from 'app/shared/model/category.model';
import {CategoryService} from 'app/entities/category';
import {ICounselor} from 'app/shared/model/counselor.model';
import {CounselorService} from 'app/entities/counselor';

@Component({
  selector: 'jhi-document-update',
  templateUrl: './document-update.component.html'
})
export class DocumentUpdateComponent implements OnInit {
  isSaving: boolean;

  rates: IRate[];

  comments: IComment[];

  categories: ICategory[];

  counselors: ICounselor[];
  publishedDateDp: any;

  editForm = this.fb.group({
    id: [],
    title: [null, [Validators.required]],
    description: [null, [Validators.required]],
    descriptionContentType: [],
    price: [null, [Validators.required]],
    publishedDate: [],
    paymentType: [],
    documentFormat: [],
    imagesGallery: [null, [Validators.required]],
    imagesGalleryContentType: [],
    tag: [null, [Validators.required]],
    rateId: [],
    commentId: [],
    gategoryId: [],
    counselorId: []
  });

  constructor(
    protected dataUtils: JhiDataUtils,
    protected jhiAlertService: JhiAlertService,
    protected documentService: DocumentService,
    protected rateService: RateService,
    protected commentService: CommentService,
    protected categoryService: CategoryService,
    protected counselorService: CounselorService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ document }) => {
      this.updateForm(document);
    });
    this.rateService
      .query({ filter: 'document-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<IRate[]>) => mayBeOk.ok),
        map((response: HttpResponse<IRate[]>) => response.body)
      )
      .subscribe(
        (res: IRate[]) => {
          if (!this.editForm.get('rateId').value) {
            this.rates = res;
          } else {
            this.rateService
              .find(this.editForm.get('rateId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<IRate>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<IRate>) => subResponse.body)
              )
              .subscribe(
                (subRes: IRate) => (this.rates = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.commentService
      .query({ filter: 'document-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<IComment[]>) => mayBeOk.ok),
        map((response: HttpResponse<IComment[]>) => response.body)
      )
      .subscribe(
        (res: IComment[]) => {
          if (!this.editForm.get('commentId').value) {
            this.comments = res;
          } else {
            this.commentService
              .find(this.editForm.get('commentId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<IComment>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<IComment>) => subResponse.body)
              )
              .subscribe(
                (subRes: IComment) => (this.comments = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.categoryService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICategory[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICategory[]>) => response.body)
      )
      .subscribe((res: ICategory[]) => (this.categories = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.counselorService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ICounselor[]>) => mayBeOk.ok),
        map((response: HttpResponse<ICounselor[]>) => response.body)
      )
      .subscribe((res: ICounselor[]) => (this.counselors = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(document: IDocument) {
    this.editForm.patchValue({
      id: document.id,
      title: document.title,
      description: document.description,
      descriptionContentType: document.descriptionContentType,
      price: document.price,
      publishedDate: document.publishedDate,
      paymentType: document.paymentType,
      documentFormat: document.documentFormat,
      imagesGallery: document.imagesGallery,
      imagesGalleryContentType: document.imagesGalleryContentType,
      tag: document.tag,
      rateId: document.rateId,
      commentId: document.commentId,
      gategoryId: document.gategoryId,
      counselorId: document.counselorId
    });
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }

  setFileData(event, field: string, isImage) {
    return new Promise((resolve, reject) => {
      if (event && event.target && event.target.files && event.target.files[0]) {
        const file = event.target.files[0];
        if (isImage && !/^image\//.test(file.type)) {
          reject(`File was expected to be an image but was found to be ${file.type}`);
        } else {
          const filedContentType: string = field + 'ContentType';
          this.dataUtils.toBase64(file, base64Data => {
            this.editForm.patchValue({
              [field]: base64Data,
              [filedContentType]: file.type
            });
          });
        }
      } else {
        reject(`Base64 data was not set as file could not be extracted from passed parameter: ${event}`);
      }
    }).then(
      () => console.log('blob added'), // sucess
      this.onError
    );
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const document = this.createFromForm();
    if (document.id !== undefined) {
      this.subscribeToSaveResponse(this.documentService.update(document));
    } else {
      this.subscribeToSaveResponse(this.documentService.create(document));
    }
  }

  private createFromForm(): IDocument {
    return {
      ...new Document(),
      id: this.editForm.get(['id']).value,
      title: this.editForm.get(['title']).value,
      descriptionContentType: this.editForm.get(['descriptionContentType']).value,
      description: this.editForm.get(['description']).value,
      price: this.editForm.get(['price']).value,
      publishedDate: this.editForm.get(['publishedDate']).value,
      paymentType: this.editForm.get(['paymentType']).value,
      documentFormat: this.editForm.get(['documentFormat']).value,
      imagesGalleryContentType: this.editForm.get(['imagesGalleryContentType']).value,
      imagesGallery: this.editForm.get(['imagesGallery']).value,
      tag: this.editForm.get(['tag']).value,
      rateId: this.editForm.get(['rateId']).value,
      commentId: this.editForm.get(['commentId']).value,
      gategoryId: this.editForm.get(['gategoryId']).value,
      counselorId: this.editForm.get(['counselorId']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IDocument>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackRateById(index: number, item: IRate) {
    return item.id;
  }

  trackCommentById(index: number, item: IComment) {
    return item.id;
  }

  trackCategoryById(index: number, item: ICategory) {
    return item.id;
  }

  trackCounselorById(index: number, item: ICounselor) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-document-heading" jhiTranslate="iCounselingApp.document.home.createOrEditLabel">Create or edit a Document</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.title" for="field_title">Title</label>
                    <input type="text" class="form-control" name="title" id="field_title"
                           formControlName="title"/>
                    <div *ngIf="editForm.get('title').invalid && (editForm.get('title').dirty || editForm.get('title').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('title').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.description" for="field_description">Description</label>
                    <div>
                        <div *ngIf="editForm.get('description').value" class="form-text text-danger clearfix">
                            <a class="pull-left" (click)="openFile(editForm.get('descriptionContentType').value, editForm.get('description').value)" jhiTranslate="entity.action.open">open</a><br>
                            <span class="pull-left">{{editForm.get('descriptionContentType').value}}, {{byteSize(editForm.get('description').value)}}</span>
                            <button type="button" (click)="editForm.patchValue({description: null});editForm.patchValue({descriptionContentType: null});"
                                    class="btn btn-secondary btn-xs pull-right">
                                <fa-icon [icon]="'times'"></fa-icon>
                            </button>
                        </div>
                        <input type="file" id="file_description" (change)="setFileData($event, 'description', false)" jhiTranslate="entity.action.addblob"/>
                    </div>
                    <input type="hidden" class="form-control" name="description" id="field_description"
                           formControlName="description"/>
                    <input type="hidden" class="form-control" name="descriptionContentType" id="field_descriptionContentType"
                           formControlName="descriptionContentType" />
                    <div *ngIf="editForm.get('description').invalid && (editForm.get('description').dirty || editForm.get('description').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('description').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.price" for="field_price">Price</label>
                    <input type="number" class="form-control" name="price" id="field_price"
                           formControlName="price"/>
                    <div *ngIf="editForm.get('price').invalid && (editForm.get('price').dirty || editForm.get('price').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('price').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.get('price')?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.publishedDate" for="field_publishedDate">Published Date</label>
                    <div class="input-group">
                        <input id="field_publishedDate" type="text" class="form-control" name="publishedDate" ngbDatepicker  #publishedDateDp="ngbDatepicker" formControlName="publishedDate"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="publishedDateDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.paymentType" for="field_paymentType">Payment Type</label>
                    <select class="form-control" name="paymentType" formControlName="paymentType" id="field_paymentType">
                        <option value="FREE">{{'iCounselingApp.PaymentType.FREE' | translate}}</option>
                        <option value="PAID">{{'iCounselingApp.PaymentType.PAID' | translate}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.documentFormat" for="field_documentFormat">Document Format</label>
                    <select class="form-control" name="documentFormat" formControlName="documentFormat" id="field_documentFormat">
                        <option value="PDF">{{'iCounselingApp.DocumentFormat.PDF' | translate}}</option>
                        <option value="DOCX">{{'iCounselingApp.DocumentFormat.DOCX' | translate}}</option>
                        <option value="DOC">{{'iCounselingApp.DocumentFormat.DOC' | translate}}</option>
                        <option value="XLSX">{{'iCounselingApp.DocumentFormat.XLSX' | translate}}</option>
                        <option value="PPT">{{'iCounselingApp.DocumentFormat.PPT' | translate}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.imagesGallery" for="field_imagesGallery">Images Gallery</label>
                    <div>
                        <div *ngIf="editForm.get('imagesGallery').value" class="form-text text-danger clearfix">
                            <a class="pull-left" (click)="openFile(editForm.get('imagesGalleryContentType').value, editForm.get('imagesGallery').value)" jhiTranslate="entity.action.open">open</a><br>
                            <span class="pull-left">{{editForm.get('imagesGalleryContentType').value}}, {{byteSize(editForm.get('imagesGallery').value)}}</span>
                            <button type="button" (click)="editForm.patchValue({imagesGallery: null});editForm.patchValue({imagesGalleryContentType: null});"
                                    class="btn btn-secondary btn-xs pull-right">
                                <fa-icon [icon]="'times'"></fa-icon>
                            </button>
                        </div>
                        <input type="file" id="file_imagesGallery" (change)="setFileData($event, 'imagesGallery', false)" jhiTranslate="entity.action.addblob"/>
                    </div>
                    <input type="hidden" class="form-control" name="imagesGallery" id="field_imagesGallery"
                           formControlName="imagesGallery"/>
                    <input type="hidden" class="form-control" name="imagesGalleryContentType" id="field_imagesGalleryContentType"
                           formControlName="imagesGalleryContentType" />
                    <div *ngIf="editForm.get('imagesGallery').invalid && (editForm.get('imagesGallery').dirty || editForm.get('imagesGallery').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('imagesGallery').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.tag" for="field_tag">Tag</label>
                    <input type="text" class="form-control" name="tag" id="field_tag"
                           formControlName="tag"/>
                    <div *ngIf="editForm.get('tag').invalid && (editForm.get('tag').dirty || editForm.get('tag').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('tag').errors.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.rate" for="field_rate">Rate</label>
                    <select class="form-control" id="field_rate" name="rate" formControlName="rateId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="rateOption.id" *ngFor="let rateOption of rates; trackBy: trackRateById">{{rateOption.index}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.comment" for="field_comment">Comment</label>
                    <select class="form-control" id="field_comment" name="comment" formControlName="commentId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="commentOption.id" *ngFor="let commentOption of comments; trackBy: trackCommentById">{{commentOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.gategory" for="field_gategory">Gategory</label>
                    <select class="form-control" id="field_gategory" name="gategory" formControlName="gategoryId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="categoryOption.id" *ngFor="let categoryOption of categories; trackBy: trackCategoryById">{{categoryOption.categoryType}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.document.counselor" for="field_counselor">Counselor</label>
                    <select class="form-control" id="field_counselor" name="counselor" formControlName="counselorId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="counselorOption.id" *ngFor="let counselorOption of counselors; trackBy: trackCounselorById">{{counselorOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
