// src/main/webapp/app/entities/document/document.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import {
  openFile,
  byteSize,
  Translate,
  ICrudGetAllAction,
  TextFormat,
  getSortState,
  IPaginationBaseState,
  getPaginationItemsNumber,
  JhiPagination
} from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './document.reducer';
import { IDocument } from 'app/shared/model/document.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface IDocumentProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export type IDocumentState = IPaginationBaseState;

export class Document extends React.Component<IDocumentProps, IDocumentState> {
  state: IDocumentState = {
    ...getSortState(this.props.location, ITEMS_PER_PAGE)
  };

  componentDidMount() {
    this.getEntities();
  }

  sort = prop => () => {
    this.setState(
      {
        order: this.state.order === 'asc' ? 'desc' : 'asc',
        sort: prop
      },
      () => this.sortEntities()
    );
  };

  sortEntities() {
    this.getEntities();
    this.props.history.push(`${this.props.location.pathname}?page=${this.state.activePage}&sort=${this.state.sort},${this.state.order}`);
  }

  handlePagination = activePage => this.setState({ activePage }, () => this.sortEntities());

  getEntities = () => {
    const { activePage, itemsPerPage, sort, order } = this.state;
    this.props.getEntities(activePage - 1, itemsPerPage, `${sort},${order}`);
  };

  render() {
    const { documentList, match, totalItems } = this.props;
    return (
      <div>
        <h2 id="document-heading">
          <Translate contentKey="iCounselingApp.document.home.title">Documents</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="iCounselingApp.document.home.createLabel">Create new Document</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={this.sort('id')}>
                  <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('title')}>
                  <Translate contentKey="iCounselingApp.document.title">Title</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('description')}>
                  <Translate contentKey="iCounselingApp.document.description">Description</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('price')}>
                  <Translate contentKey="iCounselingApp.document.price">Price</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('publishedDate')}>
                  <Translate contentKey="iCounselingApp.document.publishedDate">Published Date</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('paymentType')}>
                  <Translate contentKey="iCounselingApp.document.paymentType">Payment Type</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('documentFormat')}>
                  <Translate contentKey="iCounselingApp.document.documentFormat">Document Format</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('imagesGallery')}>
                  <Translate contentKey="iCounselingApp.document.imagesGallery">Images Gallery</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('tag')}>
                  <Translate contentKey="iCounselingApp.document.tag">Tag</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="iCounselingApp.document.rate">Rate</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="iCounselingApp.document.comment">Comment</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="iCounselingApp.document.gategory">Gategory</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="iCounselingApp.document.counselor">Counselor</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {documentList.map((document, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${document.id}`} color="link" size="sm">
                      {document.id}
                    </Button>
                  </td>
                  <td>{document.title}</td>
                  <td>
                    {document.description ? (
                      <div>
                        <a onClick={openFile(document.descriptionContentType, document.description)}>
                          <Translate contentKey="entity.action.open">Open</Translate>
                          &nbsp;
                        </a>
                        <span>
                          {document.descriptionContentType}, {byteSize(document.description)}
                        </span>
                      </div>
                    ) : null}
                  </td>
                  <td>{document.price}</td>
                  <td>
                    <TextFormat type="date" value={document.publishedDate} format={APP_LOCAL_DATE_FORMAT} />
                  </td>
                  <td>
                    <Translate contentKey={`iCounselingApp.PaymentType.${document.paymentType}`} />
                  </td>
                  <td>
                    <Translate contentKey={`iCounselingApp.DocumentFormat.${document.documentFormat}`} />
                  </td>
                  <td>
                    {document.imagesGallery ? (
                      <div>
                        <a onClick={openFile(document.imagesGalleryContentType, document.imagesGallery)}>
                          <Translate contentKey="entity.action.open">Open</Translate>
                          &nbsp;
                        </a>
                        <span>
                          {document.imagesGalleryContentType}, {byteSize(document.imagesGallery)}
                        </span>
                      </div>
                    ) : null}
                  </td>
                  <td>{document.tag}</td>
                  <td>{document.rateIndex ? <Link to={`rate/${document.rateId}`}>{document.rateIndex}</Link> : ''}</td>
                  <td>{document.commentId ? <Link to={`comment/${document.commentId}`}>{document.commentId}</Link> : ''}</td>
                  <td>
                    {document.gategoryCategoryType ? (
                      <Link to={`category/${document.gategoryId}`}>{document.gategoryCategoryType}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>{document.counselorId ? <Link to={`counselor/${document.counselorId}`}>{document.counselorId}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${document.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${document.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${document.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
        <Row className="justify-content-center">
          <JhiPagination
            items={getPaginationItemsNumber(totalItems, this.state.itemsPerPage)}
            activePage={this.state.activePage}
            onSelect={this.handlePagination}
            maxButtons={5}
          />
        </Row>
      </div>
    );
  }
}

const mapStateToProps = ({ document }: IRootState) => ({
  documentList: document.entities,
  totalItems: document.totalItems
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Document);

// src/main/webapp/app/entities/document/document.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiParseLinks, JhiAlertService, JhiDataUtils } from 'ng-jhipster';

import { IDocument } from 'app/shared/model/document.model';
import { AccountService } from 'app/core';

import { ITEMS_PER_PAGE } from 'app/shared';
import { DocumentService } from './document.service';

@Component({
  selector: 'jhi-document',
  templateUrl: './document.component.html'
})
export class DocumentComponent implements OnInit, OnDestroy {
  currentAccount: any;
  documents: IDocument[];
  error: any;
  success: any;
  eventSubscriber: Subscription;
  routeData: any;
  links: any;
  totalItems: any;
  itemsPerPage: any;
  page: any;
  predicate: any;
  previousPage: any;
  reverse: any;

  constructor(
    protected documentService: DocumentService,
    protected parseLinks: JhiParseLinks,
    protected jhiAlertService: JhiAlertService,
    protected accountService: AccountService,
    protected activatedRoute: ActivatedRoute,
    protected dataUtils: JhiDataUtils,
    protected router: Router,
    protected eventManager: JhiEventManager
  ) {
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.routeData = this.activatedRoute.data.subscribe(data => {
      this.page = data.pagingParams.page;
      this.previousPage = data.pagingParams.page;
      this.reverse = data.pagingParams.ascending;
      this.predicate = data.pagingParams.predicate;
    });
  }

  loadAll() {
    this.documentService
      .query({
        page: this.page - 1,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe(
        (res: HttpResponse<IDocument[]>) => this.paginateDocuments(res.body, res.headers),
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  loadPage(page: number) {
    if (page !== this.previousPage) {
      this.previousPage = page;
      this.transition();
    }
  }

  transition() {
    this.router.navigate(['/document'], {
      queryParams: {
        page: this.page,
        size: this.itemsPerPage,
        sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
      }
    });
    this.loadAll();
  }

  clear() {
    this.page = 0;
    this.router.navigate([
      '/document',
      {
        page: this.page,
        sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
      }
    ]);
    this.loadAll();
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInDocuments();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IDocument) {
    return item.id;
  }

  byteSize(field) {
    return this.dataUtils.byteSize(field);
  }

  openFile(contentType, field) {
    return this.dataUtils.openFile(contentType, field);
  }

  registerChangeInDocuments() {
    this.eventSubscriber = this.eventManager.subscribe('documentListModification', response => this.loadAll());
  }

  sort() {
    const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateDocuments(data: IDocument[], headers: HttpHeaders) {
    this.links = this.parseLinks.parse(headers.get('link'));
    this.totalItems = parseInt(headers.get('X-Total-Count'), 10);
    this.documents = data;
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="iCounselingApp.document.home.title">Documents</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-document" [routerLink]="['/document/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="iCounselingApp.document.home.createLabel">
            Create new Document
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="documents?.length === 0">
        <span jhiTranslate="iCounselingApp.document.home.notFound">No documents found</span>
    </div>
    <div class="table-responsive" *ngIf="documents?.length > 0">
        <table class="table table-striped">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="transition.bind(this)">
            <th jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="title"><span jhiTranslate="iCounselingApp.document.title">Title</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="description"><span jhiTranslate="iCounselingApp.document.description">Description</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="price"><span jhiTranslate="iCounselingApp.document.price">Price</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="publishedDate"><span jhiTranslate="iCounselingApp.document.publishedDate">Published Date</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="paymentType"><span jhiTranslate="iCounselingApp.document.paymentType">Payment Type</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="documentFormat"><span jhiTranslate="iCounselingApp.document.documentFormat">Document Format</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="imagesGallery"><span jhiTranslate="iCounselingApp.document.imagesGallery">Images Gallery</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="tag"><span jhiTranslate="iCounselingApp.document.tag">Tag</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="rateIndex"><span jhiTranslate="iCounselingApp.document.rate">Rate</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="commentId"><span jhiTranslate="iCounselingApp.document.comment">Comment</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="gategoryCategoryType"><span jhiTranslate="iCounselingApp.document.gategory">Gategory</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="counselorId"><span jhiTranslate="iCounselingApp.document.counselor">Counselor</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let document of documents ;trackBy: trackId">
                <td><a [routerLink]="['/document', document.id, 'view' ]">{{document.id}}</a></td>
                <td>{{document.title}}</td>
                <td>
                    <a *ngIf="document.description" (click)="openFile(document.descriptionContentType, document.description)" jhiTranslate="entity.action.open">open</a>
                    <span *ngIf="document.description">{{document.descriptionContentType}}, {{byteSize(document.description)}}</span>
                </td>
                <td>{{document.price}}</td>
                <td>{{document.publishedDate | date:'mediumDate'}}</td>
                <td jhiTranslate="{{'iCounselingApp.PaymentType.' + document.paymentType}}">{{document.paymentType}}</td>
                <td jhiTranslate="{{'iCounselingApp.DocumentFormat.' + document.documentFormat}}">{{document.documentFormat}}</td>
                <td>
                    <a *ngIf="document.imagesGallery" (click)="openFile(document.imagesGalleryContentType, document.imagesGallery)" jhiTranslate="entity.action.open">open</a>
                    <span *ngIf="document.imagesGallery">{{document.imagesGalleryContentType}}, {{byteSize(document.imagesGallery)}}</span>
                </td>
                <td>{{document.tag}}</td>
                <td>
                    <div *ngIf="document.rateId">
                        <a [routerLink]="['../rate', document.rateId , 'view' ]" >{{document.rateIndex}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="document.commentId">
                        <a [routerLink]="['../comment', document.commentId , 'view' ]" >{{document.commentId}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="document.gategoryId">
                        <a [routerLink]="['../category', document.gategoryId , 'view' ]" >{{document.gategoryCategoryType}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="document.counselorId">
                        <a [routerLink]="['../counselor', document.counselorId , 'view' ]" >{{document.counselorId}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/document', document.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/document', document.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'document', { outlets: { popup: document.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div [hidden]="documents?.length === 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [maxSize]="5" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>
        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="page" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage(page)"></ngb-pagination>
        </div>
    </div>
</div>
