// src/main/webapp/app/entities/counselor/counselor-update.component.ts
import {Component, OnInit} from '@angular/core';
import {HttpErrorResponse, HttpResponse} from '@angular/common/http';
import {FormBuilder, Validators} from '@angular/forms';
import {ActivatedRoute} from '@angular/router';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {JhiAlertService} from 'ng-jhipster';
import {Counselor, ICounselor} from 'app/shared/model/counselor.model';
import {CounselorService} from './counselor.service';
import {IEducation} from 'app/shared/model/education.model';
import {EducationService} from 'app/entities/education';
import {IScore} from 'app/shared/model/score.model';
import {ScoreService} from 'app/entities/score';
import {IUser, UserService} from 'app/core';

@Component({
  selector: 'jhi-counselor-update',
  templateUrl: './counselor-update.component.html'
})
export class CounselorUpdateComponent implements OnInit {
  isSaving: boolean;

  educations: IEducation[];

  scores: IScore[];

  users: IUser[];

  editForm = this.fb.group({
    id: [],
    consultantType: [null, [Validators.required]],
    educationId: [],
    scoreId: [],
    userId: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected counselorService: CounselorService,
    protected educationService: EducationService,
    protected scoreService: ScoreService,
    protected userService: UserService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ counselor }) => {
      this.updateForm(counselor);
    });
    this.educationService
      .query({ filter: 'counselor-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<IEducation[]>) => mayBeOk.ok),
        map((response: HttpResponse<IEducation[]>) => response.body)
      )
      .subscribe(
        (res: IEducation[]) => {
          if (!!this.editForm.get('educationId').value) {
            this.educations = res;
          } else {
            this.educationService
              .find(this.editForm.get('educationId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<IEducation>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<IEducation>) => subResponse.body)
              )
              .subscribe(
                (subRes: IEducation) => (this.educations = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.scoreService
      .query({ filter: 'counselor-is-null' })
      .pipe(
        filter((mayBeOk: HttpResponse<IScore[]>) => mayBeOk.ok),
        map((response: HttpResponse<IScore[]>) => response.body)
      )
      .subscribe(
        (res: IScore[]) => {
          if (!!this.editForm.get('scoreId').value) {
            this.scores = res;
          } else {
            this.scoreService
              .find(this.editForm.get('scoreId').value)
              .pipe(
                filter((subResMayBeOk: HttpResponse<IScore>) => subResMayBeOk.ok),
                map((subResponse: HttpResponse<IScore>) => subResponse.body)
              )
              .subscribe(
                (subRes: IScore) => (this.scores = [subRes].concat(res)),
                (subRes: HttpErrorResponse) => this.onError(subRes.message)
              );
          }
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.userService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IUser[]>) => mayBeOk.ok),
        map((response: HttpResponse<IUser[]>) => response.body)
      )
      .subscribe((res: IUser[]) => (this.users = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(counselor: ICounselor) {
    this.editForm.patchValue({
      id: counselor.id,
      consultantType: counselor.consultantType,
      educationId: counselor.educationId,
      scoreId: counselor.scoreId,
      userId: counselor.userId
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const counselor = this.createFromForm();
    if (counselor.id !== undefined) {
      this.subscribeToSaveResponse(this.counselorService.update(counselor));
    } else {
      this.subscribeToSaveResponse(this.counselorService.create(counselor));
    }
  }

  private createFromForm(): ICounselor {
    return {
      ...new Counselor(),
      id: this.editForm.get(['id']).value,
      consultantType: this.editForm.get(['consultantType']).value,
      educationId: this.editForm.get(['educationId']).value,
      scoreId: this.editForm.get(['scoreId']).value,
      userId: this.editForm.get(['userId']).value
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICounselor>>) {
    result.subscribe(() => this.onSaveSuccess(), () => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackEducationById(index: number, item: IEducation) {
    return item.id;
  }

  trackScoreById(index: number, item: IScore) {
    return item.id;
  }

  trackUserById(index: number, item: IUser) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-counselor-heading" jhiTranslate="iCounselingApp.counselor.home.createOrEditLabel">Create or edit a Counselor</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!editForm.get('id').value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                           readonly/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.counselor.consultantType" for="field_consultantType">Consultant Type</label>
                    <select class="form-control" name="consultantType" formControlName="consultantType" id="field_consultantType">
                        <option value="PSYCHOLOGY">{{'iCounselingApp.ConsultantType.PSYCHOLOGY' | translate}}</option>
                        <option value="LEGAL">{{'iCounselingApp.ConsultantType.LEGAL' | translate}}</option>
                        <option value="FINANCIAL">{{'iCounselingApp.ConsultantType.FINANCIAL' | translate}}</option>
                        <option value="EDUCATIONAL">{{'iCounselingApp.ConsultantType.EDUCATIONAL' | translate}}</option>
                        <option value="MEDICAL">{{'iCounselingApp.ConsultantType.MEDICAL' | translate}}</option>
                        <option value="INDUSTY">{{'iCounselingApp.ConsultantType.INDUSTY' | translate}}</option>
                        <option value="COMPUTER">{{'iCounselingApp.ConsultantType.COMPUTER' | translate}}</option>
                        <option value="MUSIC">{{'iCounselingApp.ConsultantType.MUSIC' | translate}}</option>
                        <option value="ART">{{'iCounselingApp.ConsultantType.ART' | translate}}</option>
                        <option value="AGRICULTURE">{{'iCounselingApp.ConsultantType.AGRICULTURE' | translate}}</option>
                        <option value="ANIMAL_HUSBANDRY">{{'iCounselingApp.ConsultantType.ANIMAL_HUSBANDRY' | translate}}</option>
                        <option value="SPORTS">{{'iCounselingApp.ConsultantType.SPORTS' | translate}}</option>
                        <option value="RELIGIOUS">{{'iCounselingApp.ConsultantType.RELIGIOUS' | translate}}</option>
                        <option value="REGISTRATION_OF_DOCUMENTS">{{'iCounselingApp.ConsultantType.REGISTRATION_OF_DOCUMENTS' | translate}}</option>
                    </select>
                    <div *ngIf="editForm.get('consultantType').invalid && (editForm.get('consultantType').dirty || editForm.get('consultantType').touched)">
                        <small class="form-text text-danger"
                               *ngIf="editForm.get('consultantType').errors.required" jhiTranslate="entity.validation.required">
                            This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.counselor.education" for="field_education">Education</label>
                    <select class="form-control" id="field_education" name="education" formControlName="educationId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="educationOption.id" *ngFor="let educationOption of educations; trackBy: trackEducationById">{{educationOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.counselor.score" for="field_score">Score</label>
                    <select class="form-control" id="field_score" name="score" formControlName="scoreId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="scoreOption.id" *ngFor="let scoreOption of scores; trackBy: trackScoreById">{{scoreOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="iCounselingApp.counselor.user"
                           for="field_user">User</label>
                    <select class="form-control" id="field_user" name="user" formControlName="userId">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="userOption.id"
                                *ngFor="let userOption of users; trackBy: trackUserById">{{userOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/counselor/counselor-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IEducation } from 'app/shared/model/education.model';
import { getEntities as getEducations } from 'app/entities/education/education.reducer';
import { IScore } from 'app/shared/model/score.model';
import { getEntities as getScores } from 'app/entities/score/score.reducer';
import { IUser } from 'app/shared/model/user.model';
import { getUsers } from 'app/modules/administration/user-management/user-management.reducer';
import { getEntity, updateEntity, createEntity, reset } from './counselor.reducer';
import { ICounselor } from 'app/shared/model/counselor.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer, convertDateTimeToServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ICounselorUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface ICounselorUpdateState {
  isNew: boolean;
  educationId: string;
  scoreId: string;
  userId: string;
}

export class CounselorUpdate extends React.Component<ICounselorUpdateProps, ICounselorUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      educationId: '0',
      scoreId: '0',
      userId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getEducations();
    this.props.getScores();
    this.props.getUsers();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { counselorEntity } = this.props;
      const entity = {
        ...counselorEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/counselor');
  };

  render() {
    const { counselorEntity, educations, scores, users, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="iCounselingApp.counselor.home.createOrEditLabel">
              <Translate contentKey="iCounselingApp.counselor.home.createOrEditLabel">Create or edit a Counselor</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : counselorEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="counselor-id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="counselor-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="consultantTypeLabel" for="counselor-consultantType">
                    <Translate contentKey="iCounselingApp.counselor.consultantType">Consultant Type</Translate>
                  </Label>
                  <AvInput
                    id="counselor-consultantType"
                    type="select"
                    className="form-control"
                    name="consultantType"
                    value={(!isNew && counselorEntity.consultantType) || 'PSYCHOLOGY'}
                  >
                    <option value="PSYCHOLOGY">
                      <Translate contentKey="iCounselingApp.ConsultantType.PSYCHOLOGY" />
                    </option>
                    <option value="LEGAL">
                      <Translate contentKey="iCounselingApp.ConsultantType.LEGAL" />
                    </option>
                    <option value="FINANCIAL">
                      <Translate contentKey="iCounselingApp.ConsultantType.FINANCIAL" />
                    </option>
                    <option value="EDUCATIONAL">
                      <Translate contentKey="iCounselingApp.ConsultantType.EDUCATIONAL" />
                    </option>
                    <option value="MEDICAL">
                      <Translate contentKey="iCounselingApp.ConsultantType.MEDICAL" />
                    </option>
                    <option value="INDUSTY">
                      <Translate contentKey="iCounselingApp.ConsultantType.INDUSTY" />
                    </option>
                    <option value="COMPUTER">
                      <Translate contentKey="iCounselingApp.ConsultantType.COMPUTER" />
                    </option>
                    <option value="MUSIC">
                      <Translate contentKey="iCounselingApp.ConsultantType.MUSIC" />
                    </option>
                    <option value="ART">
                      <Translate contentKey="iCounselingApp.ConsultantType.ART" />
                    </option>
                    <option value="AGRICULTURE">
                      <Translate contentKey="iCounselingApp.ConsultantType.AGRICULTURE" />
                    </option>
                    <option value="ANIMAL_HUSBANDRY">
                      <Translate contentKey="iCounselingApp.ConsultantType.ANIMAL_HUSBANDRY" />
                    </option>
                    <option value="SPORTS">
                      <Translate contentKey="iCounselingApp.ConsultantType.SPORTS" />
                    </option>
                    <option value="RELIGIOUS">
                      <Translate contentKey="iCounselingApp.ConsultantType.RELIGIOUS" />
                    </option>
                    <option value="REGISTRATION_OF_DOCUMENTS">
                      <Translate contentKey="iCounselingApp.ConsultantType.REGISTRATION_OF_DOCUMENTS" />
                    </option>
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="counselor-education">
                    <Translate contentKey="iCounselingApp.counselor.education">Education</Translate>
                  </Label>
                  <AvInput id="counselor-education" type="select" className="form-control" name="educationId">
                    <option value="" key="0" />
                    {educations
                      ? educations.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="counselor-score">
                    <Translate contentKey="iCounselingApp.counselor.score">Score</Translate>
                  </Label>
                  <AvInput id="counselor-score" type="select" className="form-control" name="scoreId">
                    <option value="" key="0" />
                    {scores
                      ? scores.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="counselor-user">
                    <Translate contentKey="iCounselingApp.counselor.user">User</Translate>
                  </Label>
                  <AvInput id="counselor-user" type="select" className="form-control" name="userId">
                    <option value="" key="0" />
                    {users
                      ? users.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.id}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/counselor" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  educations: storeState.education.entities,
  scores: storeState.score.entities,
  users: storeState.userManagement.users,
  counselorEntity: storeState.counselor.entity,
  loading: storeState.counselor.loading,
  updating: storeState.counselor.updating,
  updateSuccess: storeState.counselor.updateSuccess
});

const mapDispatchToProps = {
  getEducations,
  getScores,
  getUsers,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CounselorUpdate);
