// src/main/webapp/app/entities/counselor/counselor.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiParseLinks, JhiAlertService } from 'ng-jhipster';

import { ICounselor } from 'app/shared/model/counselor.model';
import { AccountService } from 'app/core';

import { ITEMS_PER_PAGE } from 'app/shared';
import { CounselorService } from './counselor.service';

@Component({
  selector: 'jhi-counselor',
  templateUrl: './counselor.component.html'
})
export class CounselorComponent implements OnInit, OnDestroy {
  currentAccount: any;
  counselors: ICounselor[];
  error: any;
  success: any;
  eventSubscriber: Subscription;
  routeData: any;
  links: any;
  totalItems: any;
  itemsPerPage: any;
  page: any;
  predicate: any;
  previousPage: any;
  reverse: any;

  constructor(
    protected counselorService: CounselorService,
    protected parseLinks: JhiParseLinks,
    protected jhiAlertService: JhiAlertService,
    protected accountService: AccountService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager
  ) {
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.routeData = this.activatedRoute.data.subscribe(data => {
      this.page = data.pagingParams.page;
      this.previousPage = data.pagingParams.page;
      this.reverse = data.pagingParams.ascending;
      this.predicate = data.pagingParams.predicate;
    });
  }

  loadAll() {
    this.counselorService
      .query({
        page: this.page - 1,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe(
        (res: HttpResponse<ICounselor[]>) => this.paginateCounselors(res.body, res.headers),
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  loadPage(page: number) {
    if (page !== this.previousPage) {
      this.previousPage = page;
      this.transition();
    }
  }

  transition() {
    this.router.navigate(['/counselor'], {
      queryParams: {
        page: this.page,
        size: this.itemsPerPage,
        sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
      }
    });
    this.loadAll();
  }

  clear() {
    this.page = 0;
    this.router.navigate([
      '/counselor',
      {
        page: this.page,
        sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
      }
    ]);
    this.loadAll();
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInCounselors();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: ICounselor) {
    return item.id;
  }

  registerChangeInCounselors() {
    this.eventSubscriber = this.eventManager.subscribe('counselorListModification', response => this.loadAll());
  }

  sort() {
    const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateCounselors(data: ICounselor[], headers: HttpHeaders) {
    this.links = this.parseLinks.parse(headers.get('link'));
    this.totalItems = parseInt(headers.get('X-Total-Count'), 10);
    this.counselors = data;
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="iCounselingApp.counselor.home.title">Counselors</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-counselor" [routerLink]="['/counselor/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="iCounselingApp.counselor.home.createLabel">
            Create new Counselor
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="alert alert-warning" *ngIf="counselors?.length === 0">
        <span jhiTranslate="iCounselingApp.counselor.home.notFound">No counselors found</span>
    </div>
    <div class="table-responsive" *ngIf="counselors?.length > 0">
        <table class="table table-striped">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="transition.bind(this)">
                <th jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span>
                    <fa-icon [icon]="'sort'"></fa-icon>
                </th>
                <th jhiSortBy="consultantType"><span jhiTranslate="iCounselingApp.counselor.consultantType">Consultant Type</span>
                    <fa-icon [icon]="'sort'"></fa-icon>
                </th>
                <th jhiSortBy="educationId"><span jhiTranslate="iCounselingApp.counselor.education">Education</span>
                    <fa-icon [icon]="'sort'"></fa-icon>
                </th>
                <th jhiSortBy="scoreId"><span jhiTranslate="iCounselingApp.counselor.score">Score</span>
                    <fa-icon [icon]="'sort'"></fa-icon>
                </th>
                <th jhiSortBy="userId"><span jhiTranslate="iCounselingApp.counselor.user">User</span>
                    <fa-icon [icon]="'sort'"></fa-icon>
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let counselor of counselors ;trackBy: trackId">
                <td><a [routerLink]="['/counselor', counselor.id, 'view' ]">{{counselor.id}}</a></td>
                <td jhiTranslate="{{'iCounselingApp.ConsultantType.' + counselor.consultantType}}">{{counselor.consultantType}}</td>
                <td>
                    <div *ngIf="counselor.educationId">
                        <a [routerLink]="['../education', counselor.educationId , 'view' ]">{{counselor.educationId}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="counselor.scoreId">
                        <a [routerLink]="['../score', counselor.scoreId , 'view' ]">{{counselor.scoreId}}</a>
                    </div>
                </td>
                <td>
                    {{counselor.userId}}
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/counselor', counselor.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/counselor', counselor.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'counselor', { outlets: { popup: counselor.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div [hidden]="counselors?.length === 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [maxSize]="5" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>
        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="page" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage(page)"></ngb-pagination>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/counselor/counselor.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAllAction, getSortState, IPaginationBaseState, getPaginationItemsNumber, JhiPagination } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './counselor.reducer';
import { ICounselor } from 'app/shared/model/counselor.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';

export interface ICounselorProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export type ICounselorState = IPaginationBaseState;

export class Counselor extends React.Component<ICounselorProps, ICounselorState> {
  state: ICounselorState = {
    ...getSortState(this.props.location, ITEMS_PER_PAGE)
  };

  componentDidMount() {
    this.getEntities();
  }

  sort = prop => () => {
    this.setState(
      {
        order: this.state.order === 'asc' ? 'desc' : 'asc',
        sort: prop
      },
      () => this.sortEntities()
    );
  };

  sortEntities() {
    this.getEntities();
    this.props.history.push(`${this.props.location.pathname}?page=${this.state.activePage}&sort=${this.state.sort},${this.state.order}`);
  }

  handlePagination = activePage => this.setState({ activePage }, () => this.sortEntities());

  getEntities = () => {
    const { activePage, itemsPerPage, sort, order } = this.state;
    this.props.getEntities(activePage - 1, itemsPerPage, `${sort},${order}`);
  };

  render() {
    const { counselorList, match, totalItems } = this.props;
    return (
      <div>
        <h2 id="counselor-heading">
          <Translate contentKey="iCounselingApp.counselor.home.title">Counselors</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity" id="jh-create-entity">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="iCounselingApp.counselor.home.createLabel">Create new Counselor</Translate>
          </Link>
        </h2>
        <div className="table-responsive">
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={this.sort('id')}>
                  <Translate contentKey="global.field.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={this.sort('consultantType')}>
                  <Translate contentKey="iCounselingApp.counselor.consultantType">Consultant Type</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="iCounselingApp.counselor.education">Education</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="iCounselingApp.counselor.score">Score</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="iCounselingApp.counselor.user">User</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {counselorList.map((counselor, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${counselor.id}`} color="link" size="sm">
                      {counselor.id}
                    </Button>
                  </td>
                  <td>
                    <Translate contentKey={`iCounselingApp.ConsultantType.${counselor.consultantType}`} />
                  </td>
                  <td>{counselor.educationId ? <Link to={`education/${counselor.educationId}`}>{counselor.educationId}</Link> : ''}</td>
                  <td>{counselor.scoreId ? <Link to={`score/${counselor.scoreId}`}>{counselor.scoreId}</Link> : ''}</td>
                  <td>{counselor.userId ? counselor.userId : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${counselor.id}`} color="info" size="sm">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${counselor.id}/edit`} color="primary" size="sm">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${counselor.id}/delete`} color="danger" size="sm">
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
        <Row className="justify-content-center">
          <JhiPagination
            items={getPaginationItemsNumber(totalItems, this.state.itemsPerPage)}
            activePage={this.state.activePage}
            onSelect={this.handlePagination}
            maxButtons={5}
          />
        </Row>
      </div>
    );
  }
}

const mapStateToProps = ({ counselor }: IRootState) => ({
  counselorList: counselor.entities,
  totalItems: counselor.totalItems
});

const mapDispatchToProps = {
  getEntities
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Counselor);
