// src/main/webapp/app/entities/library/library-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './library.reducer';
import { ILibrary } from 'app/shared/model/library.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ILibraryDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class LibraryDetail extends React.Component<ILibraryDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { libraryEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="iCounselingApp.library.detail.title">Library</Translate> [<b>{libraryEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="name">
                <Translate contentKey="iCounselingApp.library.name">Name</Translate>
              </span>
            </dt>
            <dd>{libraryEntity.name}</dd>
            <dt>
              <span id="creationTime">
                <Translate contentKey="iCounselingApp.library.creationTime">Creation Time</Translate>
              </span>
            </dt>
            <dd>
              <TextFormat value={libraryEntity.creationTime} type="date" format={APP_LOCAL_DATE_FORMAT} />
            </dd>
            <dt>
              <Translate contentKey="iCounselingApp.library.visitor">Visitor</Translate>
            </dt>
            <dd>{libraryEntity.visitorId ? libraryEntity.visitorId : ''}</dd>
          </dl>
          <Button tag={Link} to="/entity/library" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/library/${libraryEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ library }: IRootState) => ({
  libraryEntity: library.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(LibraryDetail);

// src/main/webapp/app/entities/library/library-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ILibrary } from 'app/shared/model/library.model';

@Component({
  selector: 'jhi-library-detail',
  templateUrl: './library-detail.component.html'
})
export class LibraryDetailComponent implements OnInit {
  library: ILibrary;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit() {
    this.activatedRoute.data.subscribe(({ library }) => {
      this.library = library;
    });
  }

  previousState() {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="library">
            <h2><span jhiTranslate="iCounselingApp.library.detail.title">Library</span> {{library.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="iCounselingApp.library.name">Name</span></dt>
                <dd>
                    <span>{{library.name}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.library.creationTime">Creation Time</span></dt>
                <dd>
                    <span>{{library.creationTime}}</span>
                </dd>
                <dt><span jhiTranslate="iCounselingApp.library.visitor">Visitor</span></dt>
                <dd>
                    <div *ngIf="library.visitorId">
                        <a [routerLink]="['/visitor', library.visitorId, 'view']">{{library.visitorId}}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/library', library.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>
